/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"fmt"
)

// PlanTier the model 'PlanTier'
type PlanTier string

// List of PlanTier
const (
	PLANTIER_STARTER PlanTier = "starter"
	PLANTIER_BUSINESS PlanTier = "business"
	PLANTIER_PROFESSIONAL PlanTier = "professional"
	PLANTIER_ENTERPRISE PlanTier = "enterprise"
)

// All allowed values of PlanTier enum
var AllowedPlanTierEnumValues = []PlanTier{
	"starter",
	"business",
	"professional",
	"enterprise",
}

func (v *PlanTier) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PlanTier(value)
	for _, existing := range AllowedPlanTierEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PlanTier", value)
}

// NewPlanTierFromValue returns a pointer to a valid PlanTier
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPlanTierFromValue(v string) (*PlanTier, error) {
	ev := PlanTier(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PlanTier: valid values are %v", v, AllowedPlanTierEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PlanTier) IsValid() bool {
	for _, existing := range AllowedPlanTierEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PlanTier value
func (v PlanTier) Ptr() *PlanTier {
	return &v
}

type NullablePlanTier struct {
	value *PlanTier
	isSet bool
}

func (v NullablePlanTier) Get() *PlanTier {
	return v.value
}

func (v *NullablePlanTier) Set(val *PlanTier) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanTier) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanTier(val *PlanTier) *NullablePlanTier {
	return &NullablePlanTier{value: val, isSet: true}
}

func (v NullablePlanTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

