/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the Plan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Plan{}

// Plan struct for Plan
type Plan struct {
	Tier *PlanTier `json:"tier,omitempty"`
	MonthlyPriceUsd NullableFloat32 `json:"monthly_price_usd,omitempty"`
	YearlyPriceUsd NullableFloat32 `json:"yearly_price_usd,omitempty"`
	MonthlyTransactionLimit NullableInt32 `json:"monthly_transaction_limit,omitempty"`
	OverageCostPerTx *float32 `json:"overage_cost_per_tx,omitempty"`
	WebhookSupport *bool `json:"webhook_support,omitempty"`
	WebhookLimit NullableInt32 `json:"webhook_limit,omitempty"`
	IpWhitelist *bool `json:"ip_whitelist,omitempty"`
	ApiRateLimitPerMinute *int32 `json:"api_rate_limit_per_minute,omitempty"`
	ApiRateLimitPerHour *int32 `json:"api_rate_limit_per_hour,omitempty"`
	CustomPricing *bool `json:"custom_pricing,omitempty"`
}

// NewPlan instantiates a new Plan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlan() *Plan {
	this := Plan{}
	return &this
}

// NewPlanWithDefaults instantiates a new Plan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanWithDefaults() *Plan {
	this := Plan{}
	return &this
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *Plan) GetTier() PlanTier {
	if o == nil || IsNil(o.Tier) {
		var ret PlanTier
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetTierOk() (*PlanTier, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *Plan) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given PlanTier and assigns it to the Tier field.
func (o *Plan) SetTier(v PlanTier) {
	o.Tier = &v
}

// GetMonthlyPriceUsd returns the MonthlyPriceUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Plan) GetMonthlyPriceUsd() float32 {
	if o == nil || IsNil(o.MonthlyPriceUsd.Get()) {
		var ret float32
		return ret
	}
	return *o.MonthlyPriceUsd.Get()
}

// GetMonthlyPriceUsdOk returns a tuple with the MonthlyPriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Plan) GetMonthlyPriceUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyPriceUsd.Get(), o.MonthlyPriceUsd.IsSet()
}

// HasMonthlyPriceUsd returns a boolean if a field has been set.
func (o *Plan) HasMonthlyPriceUsd() bool {
	if o != nil && o.MonthlyPriceUsd.IsSet() {
		return true
	}

	return false
}

// SetMonthlyPriceUsd gets a reference to the given NullableFloat32 and assigns it to the MonthlyPriceUsd field.
func (o *Plan) SetMonthlyPriceUsd(v float32) {
	o.MonthlyPriceUsd.Set(&v)
}
// SetMonthlyPriceUsdNil sets the value for MonthlyPriceUsd to be an explicit nil
func (o *Plan) SetMonthlyPriceUsdNil() {
	o.MonthlyPriceUsd.Set(nil)
}

// UnsetMonthlyPriceUsd ensures that no value is present for MonthlyPriceUsd, not even an explicit nil
func (o *Plan) UnsetMonthlyPriceUsd() {
	o.MonthlyPriceUsd.Unset()
}

// GetYearlyPriceUsd returns the YearlyPriceUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Plan) GetYearlyPriceUsd() float32 {
	if o == nil || IsNil(o.YearlyPriceUsd.Get()) {
		var ret float32
		return ret
	}
	return *o.YearlyPriceUsd.Get()
}

// GetYearlyPriceUsdOk returns a tuple with the YearlyPriceUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Plan) GetYearlyPriceUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.YearlyPriceUsd.Get(), o.YearlyPriceUsd.IsSet()
}

// HasYearlyPriceUsd returns a boolean if a field has been set.
func (o *Plan) HasYearlyPriceUsd() bool {
	if o != nil && o.YearlyPriceUsd.IsSet() {
		return true
	}

	return false
}

// SetYearlyPriceUsd gets a reference to the given NullableFloat32 and assigns it to the YearlyPriceUsd field.
func (o *Plan) SetYearlyPriceUsd(v float32) {
	o.YearlyPriceUsd.Set(&v)
}
// SetYearlyPriceUsdNil sets the value for YearlyPriceUsd to be an explicit nil
func (o *Plan) SetYearlyPriceUsdNil() {
	o.YearlyPriceUsd.Set(nil)
}

// UnsetYearlyPriceUsd ensures that no value is present for YearlyPriceUsd, not even an explicit nil
func (o *Plan) UnsetYearlyPriceUsd() {
	o.YearlyPriceUsd.Unset()
}

// GetMonthlyTransactionLimit returns the MonthlyTransactionLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Plan) GetMonthlyTransactionLimit() int32 {
	if o == nil || IsNil(o.MonthlyTransactionLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.MonthlyTransactionLimit.Get()
}

// GetMonthlyTransactionLimitOk returns a tuple with the MonthlyTransactionLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Plan) GetMonthlyTransactionLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyTransactionLimit.Get(), o.MonthlyTransactionLimit.IsSet()
}

// HasMonthlyTransactionLimit returns a boolean if a field has been set.
func (o *Plan) HasMonthlyTransactionLimit() bool {
	if o != nil && o.MonthlyTransactionLimit.IsSet() {
		return true
	}

	return false
}

// SetMonthlyTransactionLimit gets a reference to the given NullableInt32 and assigns it to the MonthlyTransactionLimit field.
func (o *Plan) SetMonthlyTransactionLimit(v int32) {
	o.MonthlyTransactionLimit.Set(&v)
}
// SetMonthlyTransactionLimitNil sets the value for MonthlyTransactionLimit to be an explicit nil
func (o *Plan) SetMonthlyTransactionLimitNil() {
	o.MonthlyTransactionLimit.Set(nil)
}

// UnsetMonthlyTransactionLimit ensures that no value is present for MonthlyTransactionLimit, not even an explicit nil
func (o *Plan) UnsetMonthlyTransactionLimit() {
	o.MonthlyTransactionLimit.Unset()
}

// GetOverageCostPerTx returns the OverageCostPerTx field value if set, zero value otherwise.
func (o *Plan) GetOverageCostPerTx() float32 {
	if o == nil || IsNil(o.OverageCostPerTx) {
		var ret float32
		return ret
	}
	return *o.OverageCostPerTx
}

// GetOverageCostPerTxOk returns a tuple with the OverageCostPerTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetOverageCostPerTxOk() (*float32, bool) {
	if o == nil || IsNil(o.OverageCostPerTx) {
		return nil, false
	}
	return o.OverageCostPerTx, true
}

// HasOverageCostPerTx returns a boolean if a field has been set.
func (o *Plan) HasOverageCostPerTx() bool {
	if o != nil && !IsNil(o.OverageCostPerTx) {
		return true
	}

	return false
}

// SetOverageCostPerTx gets a reference to the given float32 and assigns it to the OverageCostPerTx field.
func (o *Plan) SetOverageCostPerTx(v float32) {
	o.OverageCostPerTx = &v
}

// GetWebhookSupport returns the WebhookSupport field value if set, zero value otherwise.
func (o *Plan) GetWebhookSupport() bool {
	if o == nil || IsNil(o.WebhookSupport) {
		var ret bool
		return ret
	}
	return *o.WebhookSupport
}

// GetWebhookSupportOk returns a tuple with the WebhookSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetWebhookSupportOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhookSupport) {
		return nil, false
	}
	return o.WebhookSupport, true
}

// HasWebhookSupport returns a boolean if a field has been set.
func (o *Plan) HasWebhookSupport() bool {
	if o != nil && !IsNil(o.WebhookSupport) {
		return true
	}

	return false
}

// SetWebhookSupport gets a reference to the given bool and assigns it to the WebhookSupport field.
func (o *Plan) SetWebhookSupport(v bool) {
	o.WebhookSupport = &v
}

// GetWebhookLimit returns the WebhookLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Plan) GetWebhookLimit() int32 {
	if o == nil || IsNil(o.WebhookLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.WebhookLimit.Get()
}

// GetWebhookLimitOk returns a tuple with the WebhookLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Plan) GetWebhookLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookLimit.Get(), o.WebhookLimit.IsSet()
}

// HasWebhookLimit returns a boolean if a field has been set.
func (o *Plan) HasWebhookLimit() bool {
	if o != nil && o.WebhookLimit.IsSet() {
		return true
	}

	return false
}

// SetWebhookLimit gets a reference to the given NullableInt32 and assigns it to the WebhookLimit field.
func (o *Plan) SetWebhookLimit(v int32) {
	o.WebhookLimit.Set(&v)
}
// SetWebhookLimitNil sets the value for WebhookLimit to be an explicit nil
func (o *Plan) SetWebhookLimitNil() {
	o.WebhookLimit.Set(nil)
}

// UnsetWebhookLimit ensures that no value is present for WebhookLimit, not even an explicit nil
func (o *Plan) UnsetWebhookLimit() {
	o.WebhookLimit.Unset()
}

// GetIpWhitelist returns the IpWhitelist field value if set, zero value otherwise.
func (o *Plan) GetIpWhitelist() bool {
	if o == nil || IsNil(o.IpWhitelist) {
		var ret bool
		return ret
	}
	return *o.IpWhitelist
}

// GetIpWhitelistOk returns a tuple with the IpWhitelist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetIpWhitelistOk() (*bool, bool) {
	if o == nil || IsNil(o.IpWhitelist) {
		return nil, false
	}
	return o.IpWhitelist, true
}

// HasIpWhitelist returns a boolean if a field has been set.
func (o *Plan) HasIpWhitelist() bool {
	if o != nil && !IsNil(o.IpWhitelist) {
		return true
	}

	return false
}

// SetIpWhitelist gets a reference to the given bool and assigns it to the IpWhitelist field.
func (o *Plan) SetIpWhitelist(v bool) {
	o.IpWhitelist = &v
}

// GetApiRateLimitPerMinute returns the ApiRateLimitPerMinute field value if set, zero value otherwise.
func (o *Plan) GetApiRateLimitPerMinute() int32 {
	if o == nil || IsNil(o.ApiRateLimitPerMinute) {
		var ret int32
		return ret
	}
	return *o.ApiRateLimitPerMinute
}

// GetApiRateLimitPerMinuteOk returns a tuple with the ApiRateLimitPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetApiRateLimitPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.ApiRateLimitPerMinute) {
		return nil, false
	}
	return o.ApiRateLimitPerMinute, true
}

// HasApiRateLimitPerMinute returns a boolean if a field has been set.
func (o *Plan) HasApiRateLimitPerMinute() bool {
	if o != nil && !IsNil(o.ApiRateLimitPerMinute) {
		return true
	}

	return false
}

// SetApiRateLimitPerMinute gets a reference to the given int32 and assigns it to the ApiRateLimitPerMinute field.
func (o *Plan) SetApiRateLimitPerMinute(v int32) {
	o.ApiRateLimitPerMinute = &v
}

// GetApiRateLimitPerHour returns the ApiRateLimitPerHour field value if set, zero value otherwise.
func (o *Plan) GetApiRateLimitPerHour() int32 {
	if o == nil || IsNil(o.ApiRateLimitPerHour) {
		var ret int32
		return ret
	}
	return *o.ApiRateLimitPerHour
}

// GetApiRateLimitPerHourOk returns a tuple with the ApiRateLimitPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetApiRateLimitPerHourOk() (*int32, bool) {
	if o == nil || IsNil(o.ApiRateLimitPerHour) {
		return nil, false
	}
	return o.ApiRateLimitPerHour, true
}

// HasApiRateLimitPerHour returns a boolean if a field has been set.
func (o *Plan) HasApiRateLimitPerHour() bool {
	if o != nil && !IsNil(o.ApiRateLimitPerHour) {
		return true
	}

	return false
}

// SetApiRateLimitPerHour gets a reference to the given int32 and assigns it to the ApiRateLimitPerHour field.
func (o *Plan) SetApiRateLimitPerHour(v int32) {
	o.ApiRateLimitPerHour = &v
}

// GetCustomPricing returns the CustomPricing field value if set, zero value otherwise.
func (o *Plan) GetCustomPricing() bool {
	if o == nil || IsNil(o.CustomPricing) {
		var ret bool
		return ret
	}
	return *o.CustomPricing
}

// GetCustomPricingOk returns a tuple with the CustomPricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plan) GetCustomPricingOk() (*bool, bool) {
	if o == nil || IsNil(o.CustomPricing) {
		return nil, false
	}
	return o.CustomPricing, true
}

// HasCustomPricing returns a boolean if a field has been set.
func (o *Plan) HasCustomPricing() bool {
	if o != nil && !IsNil(o.CustomPricing) {
		return true
	}

	return false
}

// SetCustomPricing gets a reference to the given bool and assigns it to the CustomPricing field.
func (o *Plan) SetCustomPricing(v bool) {
	o.CustomPricing = &v
}

func (o Plan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Plan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if o.MonthlyPriceUsd.IsSet() {
		toSerialize["monthly_price_usd"] = o.MonthlyPriceUsd.Get()
	}
	if o.YearlyPriceUsd.IsSet() {
		toSerialize["yearly_price_usd"] = o.YearlyPriceUsd.Get()
	}
	if o.MonthlyTransactionLimit.IsSet() {
		toSerialize["monthly_transaction_limit"] = o.MonthlyTransactionLimit.Get()
	}
	if !IsNil(o.OverageCostPerTx) {
		toSerialize["overage_cost_per_tx"] = o.OverageCostPerTx
	}
	if !IsNil(o.WebhookSupport) {
		toSerialize["webhook_support"] = o.WebhookSupport
	}
	if o.WebhookLimit.IsSet() {
		toSerialize["webhook_limit"] = o.WebhookLimit.Get()
	}
	if !IsNil(o.IpWhitelist) {
		toSerialize["ip_whitelist"] = o.IpWhitelist
	}
	if !IsNil(o.ApiRateLimitPerMinute) {
		toSerialize["api_rate_limit_per_minute"] = o.ApiRateLimitPerMinute
	}
	if !IsNil(o.ApiRateLimitPerHour) {
		toSerialize["api_rate_limit_per_hour"] = o.ApiRateLimitPerHour
	}
	if !IsNil(o.CustomPricing) {
		toSerialize["custom_pricing"] = o.CustomPricing
	}
	return toSerialize, nil
}

type NullablePlan struct {
	value *Plan
	isSet bool
}

func (v NullablePlan) Get() *Plan {
	return v.value
}

func (v *NullablePlan) Set(val *Plan) {
	v.value = val
	v.isSet = true
}

func (v NullablePlan) IsSet() bool {
	return v.isSet
}

func (v *NullablePlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlan(val *Plan) *NullablePlan {
	return &NullablePlan{value: val, isSet: true}
}

func (v NullablePlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


