/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the ListInvoices200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListInvoices200ResponseData{}

// ListInvoices200ResponseData struct for ListInvoices200ResponseData
type ListInvoices200ResponseData struct {
	Invoices []Invoice `json:"invoices,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewListInvoices200ResponseData instantiates a new ListInvoices200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInvoices200ResponseData() *ListInvoices200ResponseData {
	this := ListInvoices200ResponseData{}
	return &this
}

// NewListInvoices200ResponseDataWithDefaults instantiates a new ListInvoices200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInvoices200ResponseDataWithDefaults() *ListInvoices200ResponseData {
	this := ListInvoices200ResponseData{}
	return &this
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *ListInvoices200ResponseData) GetInvoices() []Invoice {
	if o == nil || IsNil(o.Invoices) {
		var ret []Invoice
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListInvoices200ResponseData) GetInvoicesOk() ([]Invoice, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *ListInvoices200ResponseData) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []Invoice and assigns it to the Invoices field.
func (o *ListInvoices200ResponseData) SetInvoices(v []Invoice) {
	o.Invoices = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListInvoices200ResponseData) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListInvoices200ResponseData) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListInvoices200ResponseData) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ListInvoices200ResponseData) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o ListInvoices200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListInvoices200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListInvoices200ResponseData struct {
	value *ListInvoices200ResponseData
	isSet bool
}

func (v NullableListInvoices200ResponseData) Get() *ListInvoices200ResponseData {
	return v.value
}

func (v *NullableListInvoices200ResponseData) Set(val *ListInvoices200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListInvoices200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListInvoices200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInvoices200ResponseData(val *ListInvoices200ResponseData) *NullableListInvoices200ResponseData {
	return &NullableListInvoices200ResponseData{value: val, isSet: true}
}

func (v NullableListInvoices200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInvoices200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


