/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListTransactions200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTransactions200ResponseData{}

// ListTransactions200ResponseData struct for ListTransactions200ResponseData
type ListTransactions200ResponseData struct {
	Transactions []Transaction `json:"transactions"`
	Pagination Pagination `json:"pagination"`
}

type _ListTransactions200ResponseData ListTransactions200ResponseData

// NewListTransactions200ResponseData instantiates a new ListTransactions200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTransactions200ResponseData(transactions []Transaction, pagination Pagination) *ListTransactions200ResponseData {
	this := ListTransactions200ResponseData{}
	this.Transactions = transactions
	this.Pagination = pagination
	return &this
}

// NewListTransactions200ResponseDataWithDefaults instantiates a new ListTransactions200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTransactions200ResponseDataWithDefaults() *ListTransactions200ResponseData {
	this := ListTransactions200ResponseData{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *ListTransactions200ResponseData) GetTransactions() []Transaction {
	if o == nil {
		var ret []Transaction
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *ListTransactions200ResponseData) GetTransactionsOk() ([]Transaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *ListTransactions200ResponseData) SetTransactions(v []Transaction) {
	o.Transactions = v
}

// GetPagination returns the Pagination field value
func (o *ListTransactions200ResponseData) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListTransactions200ResponseData) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListTransactions200ResponseData) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o ListTransactions200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTransactions200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *ListTransactions200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTransactions200ResponseData := _ListTransactions200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListTransactions200ResponseData)

	if err != nil {
		return err
	}

	*o = ListTransactions200ResponseData(varListTransactions200ResponseData)

	return err
}

type NullableListTransactions200ResponseData struct {
	value *ListTransactions200ResponseData
	isSet bool
}

func (v NullableListTransactions200ResponseData) Get() *ListTransactions200ResponseData {
	return v.value
}

func (v *NullableListTransactions200ResponseData) Set(val *ListTransactions200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListTransactions200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListTransactions200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTransactions200ResponseData(val *ListTransactions200ResponseData) *NullableListTransactions200ResponseData {
	return &NullableListTransactions200ResponseData{value: val, isSet: true}
}

func (v NullableListTransactions200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTransactions200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


