/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
	"time"
)

// checks if the GetPrices200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPrices200ResponseData{}

// GetPrices200ResponseData struct for GetPrices200ResponseData
type GetPrices200ResponseData struct {
	// USD price per unit, keyed by crypto symbol (active coins only).
	Crypto map[string]float32 `json:"crypto,omitempty"`
	// USD value of one unit of each fiat currency.
	Fiat map[string]float32 `json:"fiat,omitempty"`
	FetchedAt *time.Time `json:"fetched_at,omitempty"`
}

// NewGetPrices200ResponseData instantiates a new GetPrices200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPrices200ResponseData() *GetPrices200ResponseData {
	this := GetPrices200ResponseData{}
	return &this
}

// NewGetPrices200ResponseDataWithDefaults instantiates a new GetPrices200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPrices200ResponseDataWithDefaults() *GetPrices200ResponseData {
	this := GetPrices200ResponseData{}
	return &this
}

// GetCrypto returns the Crypto field value if set, zero value otherwise.
func (o *GetPrices200ResponseData) GetCrypto() map[string]float32 {
	if o == nil || IsNil(o.Crypto) {
		var ret map[string]float32
		return ret
	}
	return o.Crypto
}

// GetCryptoOk returns a tuple with the Crypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPrices200ResponseData) GetCryptoOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.Crypto) {
		return map[string]float32{}, false
	}
	return o.Crypto, true
}

// HasCrypto returns a boolean if a field has been set.
func (o *GetPrices200ResponseData) HasCrypto() bool {
	if o != nil && !IsNil(o.Crypto) {
		return true
	}

	return false
}

// SetCrypto gets a reference to the given map[string]float32 and assigns it to the Crypto field.
func (o *GetPrices200ResponseData) SetCrypto(v map[string]float32) {
	o.Crypto = v
}

// GetFiat returns the Fiat field value if set, zero value otherwise.
func (o *GetPrices200ResponseData) GetFiat() map[string]float32 {
	if o == nil || IsNil(o.Fiat) {
		var ret map[string]float32
		return ret
	}
	return o.Fiat
}

// GetFiatOk returns a tuple with the Fiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPrices200ResponseData) GetFiatOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.Fiat) {
		return map[string]float32{}, false
	}
	return o.Fiat, true
}

// HasFiat returns a boolean if a field has been set.
func (o *GetPrices200ResponseData) HasFiat() bool {
	if o != nil && !IsNil(o.Fiat) {
		return true
	}

	return false
}

// SetFiat gets a reference to the given map[string]float32 and assigns it to the Fiat field.
func (o *GetPrices200ResponseData) SetFiat(v map[string]float32) {
	o.Fiat = v
}

// GetFetchedAt returns the FetchedAt field value if set, zero value otherwise.
func (o *GetPrices200ResponseData) GetFetchedAt() time.Time {
	if o == nil || IsNil(o.FetchedAt) {
		var ret time.Time
		return ret
	}
	return *o.FetchedAt
}

// GetFetchedAtOk returns a tuple with the FetchedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPrices200ResponseData) GetFetchedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FetchedAt) {
		return nil, false
	}
	return o.FetchedAt, true
}

// HasFetchedAt returns a boolean if a field has been set.
func (o *GetPrices200ResponseData) HasFetchedAt() bool {
	if o != nil && !IsNil(o.FetchedAt) {
		return true
	}

	return false
}

// SetFetchedAt gets a reference to the given time.Time and assigns it to the FetchedAt field.
func (o *GetPrices200ResponseData) SetFetchedAt(v time.Time) {
	o.FetchedAt = &v
}

func (o GetPrices200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPrices200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Crypto) {
		toSerialize["crypto"] = o.Crypto
	}
	if !IsNil(o.Fiat) {
		toSerialize["fiat"] = o.Fiat
	}
	if !IsNil(o.FetchedAt) {
		toSerialize["fetched_at"] = o.FetchedAt
	}
	return toSerialize, nil
}

type NullableGetPrices200ResponseData struct {
	value *GetPrices200ResponseData
	isSet bool
}

func (v NullableGetPrices200ResponseData) Get() *GetPrices200ResponseData {
	return v.value
}

func (v *NullableGetPrices200ResponseData) Set(val *GetPrices200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPrices200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPrices200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPrices200ResponseData(val *GetPrices200ResponseData) *NullableGetPrices200ResponseData {
	return &NullableGetPrices200ResponseData{value: val, isSet: true}
}

func (v NullableGetPrices200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPrices200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


