/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"time"
)

// checks if the Invoice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Invoice{}

// Invoice struct for Invoice
type Invoice struct {
	TransactionId *string `json:"transaction_id,omitempty"`
	PurchaseType *string `json:"purchase_type,omitempty"`
	AmountFiat *float32 `json:"amount_fiat,omitempty"`
	CurrencyFiat *FiatCurrency `json:"currency_fiat,omitempty"`
	Status *string `json:"status,omitempty"`
	CryptoSymbol *CryptoSymbol `json:"crypto_symbol,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	ConfirmedAt NullableTime `json:"confirmed_at,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// NewInvoice instantiates a new Invoice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoice() *Invoice {
	this := Invoice{}
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	return &this
}

// NewInvoiceWithDefaults instantiates a new Invoice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceWithDefaults() *Invoice {
	this := Invoice{}
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *Invoice) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *Invoice) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *Invoice) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetPurchaseType returns the PurchaseType field value if set, zero value otherwise.
func (o *Invoice) GetPurchaseType() string {
	if o == nil || IsNil(o.PurchaseType) {
		var ret string
		return ret
	}
	return *o.PurchaseType
}

// GetPurchaseTypeOk returns a tuple with the PurchaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetPurchaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PurchaseType) {
		return nil, false
	}
	return o.PurchaseType, true
}

// HasPurchaseType returns a boolean if a field has been set.
func (o *Invoice) HasPurchaseType() bool {
	if o != nil && !IsNil(o.PurchaseType) {
		return true
	}

	return false
}

// SetPurchaseType gets a reference to the given string and assigns it to the PurchaseType field.
func (o *Invoice) SetPurchaseType(v string) {
	o.PurchaseType = &v
}

// GetAmountFiat returns the AmountFiat field value if set, zero value otherwise.
func (o *Invoice) GetAmountFiat() float32 {
	if o == nil || IsNil(o.AmountFiat) {
		var ret float32
		return ret
	}
	return *o.AmountFiat
}

// GetAmountFiatOk returns a tuple with the AmountFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetAmountFiatOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountFiat) {
		return nil, false
	}
	return o.AmountFiat, true
}

// HasAmountFiat returns a boolean if a field has been set.
func (o *Invoice) HasAmountFiat() bool {
	if o != nil && !IsNil(o.AmountFiat) {
		return true
	}

	return false
}

// SetAmountFiat gets a reference to the given float32 and assigns it to the AmountFiat field.
func (o *Invoice) SetAmountFiat(v float32) {
	o.AmountFiat = &v
}

// GetCurrencyFiat returns the CurrencyFiat field value if set, zero value otherwise.
func (o *Invoice) GetCurrencyFiat() FiatCurrency {
	if o == nil || IsNil(o.CurrencyFiat) {
		var ret FiatCurrency
		return ret
	}
	return *o.CurrencyFiat
}

// GetCurrencyFiatOk returns a tuple with the CurrencyFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetCurrencyFiatOk() (*FiatCurrency, bool) {
	if o == nil || IsNil(o.CurrencyFiat) {
		return nil, false
	}
	return o.CurrencyFiat, true
}

// HasCurrencyFiat returns a boolean if a field has been set.
func (o *Invoice) HasCurrencyFiat() bool {
	if o != nil && !IsNil(o.CurrencyFiat) {
		return true
	}

	return false
}

// SetCurrencyFiat gets a reference to the given FiatCurrency and assigns it to the CurrencyFiat field.
func (o *Invoice) SetCurrencyFiat(v FiatCurrency) {
	o.CurrencyFiat = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Invoice) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Invoice) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Invoice) SetStatus(v string) {
	o.Status = &v
}

// GetCryptoSymbol returns the CryptoSymbol field value if set, zero value otherwise.
func (o *Invoice) GetCryptoSymbol() CryptoSymbol {
	if o == nil || IsNil(o.CryptoSymbol) {
		var ret CryptoSymbol
		return ret
	}
	return *o.CryptoSymbol
}

// GetCryptoSymbolOk returns a tuple with the CryptoSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetCryptoSymbolOk() (*CryptoSymbol, bool) {
	if o == nil || IsNil(o.CryptoSymbol) {
		return nil, false
	}
	return o.CryptoSymbol, true
}

// HasCryptoSymbol returns a boolean if a field has been set.
func (o *Invoice) HasCryptoSymbol() bool {
	if o != nil && !IsNil(o.CryptoSymbol) {
		return true
	}

	return false
}

// SetCryptoSymbol gets a reference to the given CryptoSymbol and assigns it to the CryptoSymbol field.
func (o *Invoice) SetCryptoSymbol(v CryptoSymbol) {
	o.CryptoSymbol = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Invoice) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Invoice) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Invoice) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetConfirmedAt returns the ConfirmedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Invoice) GetConfirmedAt() time.Time {
	if o == nil || IsNil(o.ConfirmedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmedAt.Get()
}

// GetConfirmedAtOk returns a tuple with the ConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Invoice) GetConfirmedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfirmedAt.Get(), o.ConfirmedAt.IsSet()
}

// HasConfirmedAt returns a boolean if a field has been set.
func (o *Invoice) HasConfirmedAt() bool {
	if o != nil && o.ConfirmedAt.IsSet() {
		return true
	}

	return false
}

// SetConfirmedAt gets a reference to the given NullableTime and assigns it to the ConfirmedAt field.
func (o *Invoice) SetConfirmedAt(v time.Time) {
	o.ConfirmedAt.Set(&v)
}
// SetConfirmedAtNil sets the value for ConfirmedAt to be an explicit nil
func (o *Invoice) SetConfirmedAtNil() {
	o.ConfirmedAt.Set(nil)
}

// UnsetConfirmedAt ensures that no value is present for ConfirmedAt, not even an explicit nil
func (o *Invoice) UnsetConfirmedAt() {
	o.ConfirmedAt.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Invoice) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Invoice) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Invoice) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *Invoice) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o Invoice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Invoice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.PurchaseType) {
		toSerialize["purchase_type"] = o.PurchaseType
	}
	if !IsNil(o.AmountFiat) {
		toSerialize["amount_fiat"] = o.AmountFiat
	}
	if !IsNil(o.CurrencyFiat) {
		toSerialize["currency_fiat"] = o.CurrencyFiat
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CryptoSymbol) {
		toSerialize["crypto_symbol"] = o.CryptoSymbol
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.ConfirmedAt.IsSet() {
		toSerialize["confirmed_at"] = o.ConfirmedAt.Get()
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableInvoice struct {
	value *Invoice
	isSet bool
}

func (v NullableInvoice) Get() *Invoice {
	return v.value
}

func (v *NullableInvoice) Set(val *Invoice) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoice) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoice(val *Invoice) *NullableInvoice {
	return &NullableInvoice{value: val, isSet: true}
}

func (v NullableInvoice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


