/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"fmt"
)

// CryptoSymbol Supported coin/token symbol. /cryptos/list is authoritative at runtime.
type CryptoSymbol string

// List of CryptoSymbol
const (
	CRYPTOSYMBOL_BTC CryptoSymbol = "BTC"
	CRYPTOSYMBOL_LTC CryptoSymbol = "LTC"
	CRYPTOSYMBOL_DOGE CryptoSymbol = "DOGE"
	CRYPTOSYMBOL_DASH CryptoSymbol = "DASH"
	CRYPTOSYMBOL_ETH CryptoSymbol = "ETH"
	CRYPTOSYMBOL_USDT CryptoSymbol = "USDT"
	CRYPTOSYMBOL_USDC CryptoSymbol = "USDC"
	CRYPTOSYMBOL_DAI CryptoSymbol = "DAI"
	CRYPTOSYMBOL_WBTC CryptoSymbol = "WBTC"
	CRYPTOSYMBOL_SHIB CryptoSymbol = "SHIB"
	CRYPTOSYMBOL_PEPE CryptoSymbol = "PEPE"
	CRYPTOSYMBOL_LINK CryptoSymbol = "LINK"
	CRYPTOSYMBOL_UNI CryptoSymbol = "UNI"
	CRYPTOSYMBOL_AAVE CryptoSymbol = "AAVE"
	CRYPTOSYMBOL_MKR CryptoSymbol = "MKR"
)

// All allowed values of CryptoSymbol enum
var AllowedCryptoSymbolEnumValues = []CryptoSymbol{
	"BTC",
	"LTC",
	"DOGE",
	"DASH",
	"ETH",
	"USDT",
	"USDC",
	"DAI",
	"WBTC",
	"SHIB",
	"PEPE",
	"LINK",
	"UNI",
	"AAVE",
	"MKR",
}

func (v *CryptoSymbol) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CryptoSymbol(value)
	for _, existing := range AllowedCryptoSymbolEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CryptoSymbol", value)
}

// NewCryptoSymbolFromValue returns a pointer to a valid CryptoSymbol
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCryptoSymbolFromValue(v string) (*CryptoSymbol, error) {
	ev := CryptoSymbol(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CryptoSymbol: valid values are %v", v, AllowedCryptoSymbolEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CryptoSymbol) IsValid() bool {
	for _, existing := range AllowedCryptoSymbolEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CryptoSymbol value
func (v CryptoSymbol) Ptr() *CryptoSymbol {
	return &v
}

type NullableCryptoSymbol struct {
	value *CryptoSymbol
	isSet bool
}

func (v NullableCryptoSymbol) Get() *CryptoSymbol {
	return v.value
}

func (v *NullableCryptoSymbol) Set(val *CryptoSymbol) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoSymbol) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoSymbol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoSymbol(val *CryptoSymbol) *NullableCryptoSymbol {
	return &NullableCryptoSymbol{value: val, isSet: true}
}

func (v NullableCryptoSymbol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoSymbol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

