/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the ListBalances200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBalances200ResponseData{}

// ListBalances200ResponseData struct for ListBalances200ResponseData
type ListBalances200ResponseData struct {
	Balances []Balance `json:"balances,omitempty"`
}

// NewListBalances200ResponseData instantiates a new ListBalances200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBalances200ResponseData() *ListBalances200ResponseData {
	this := ListBalances200ResponseData{}
	return &this
}

// NewListBalances200ResponseDataWithDefaults instantiates a new ListBalances200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBalances200ResponseDataWithDefaults() *ListBalances200ResponseData {
	this := ListBalances200ResponseData{}
	return &this
}

// GetBalances returns the Balances field value if set, zero value otherwise.
func (o *ListBalances200ResponseData) GetBalances() []Balance {
	if o == nil || IsNil(o.Balances) {
		var ret []Balance
		return ret
	}
	return o.Balances
}

// GetBalancesOk returns a tuple with the Balances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBalances200ResponseData) GetBalancesOk() ([]Balance, bool) {
	if o == nil || IsNil(o.Balances) {
		return nil, false
	}
	return o.Balances, true
}

// HasBalances returns a boolean if a field has been set.
func (o *ListBalances200ResponseData) HasBalances() bool {
	if o != nil && !IsNil(o.Balances) {
		return true
	}

	return false
}

// SetBalances gets a reference to the given []Balance and assigns it to the Balances field.
func (o *ListBalances200ResponseData) SetBalances(v []Balance) {
	o.Balances = v
}

func (o ListBalances200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBalances200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balances) {
		toSerialize["balances"] = o.Balances
	}
	return toSerialize, nil
}

type NullableListBalances200ResponseData struct {
	value *ListBalances200ResponseData
	isSet bool
}

func (v NullableListBalances200ResponseData) Get() *ListBalances200ResponseData {
	return v.value
}

func (v *NullableListBalances200ResponseData) Set(val *ListBalances200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListBalances200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListBalances200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBalances200ResponseData(val *ListBalances200ResponseData) *NullableListBalances200ResponseData {
	return &NullableListBalances200ResponseData{value: val, isSet: true}
}

func (v NullableListBalances200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBalances200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


