/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
	"fmt"
)

// FiatCurrency the model 'FiatCurrency'
type FiatCurrency string

// List of FiatCurrency
const (
	FIATCURRENCY_USD FiatCurrency = "USD"
	FIATCURRENCY_PLN FiatCurrency = "PLN"
	FIATCURRENCY_EUR FiatCurrency = "EUR"
	FIATCURRENCY_GBP FiatCurrency = "GBP"
)

// All allowed values of FiatCurrency enum
var AllowedFiatCurrencyEnumValues = []FiatCurrency{
	"USD",
	"PLN",
	"EUR",
	"GBP",
}

func (v *FiatCurrency) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FiatCurrency(value)
	for _, existing := range AllowedFiatCurrencyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FiatCurrency", value)
}

// NewFiatCurrencyFromValue returns a pointer to a valid FiatCurrency
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFiatCurrencyFromValue(v string) (*FiatCurrency, error) {
	ev := FiatCurrency(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FiatCurrency: valid values are %v", v, AllowedFiatCurrencyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FiatCurrency) IsValid() bool {
	for _, existing := range AllowedFiatCurrencyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FiatCurrency value
func (v FiatCurrency) Ptr() *FiatCurrency {
	return &v
}

type NullableFiatCurrency struct {
	value *FiatCurrency
	isSet bool
}

func (v NullableFiatCurrency) Get() *FiatCurrency {
	return v.value
}

func (v *NullableFiatCurrency) Set(val *FiatCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableFiatCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableFiatCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiatCurrency(val *FiatCurrency) *NullableFiatCurrency {
	return &NullableFiatCurrency{value: val, isSet: true}
}

func (v NullableFiatCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiatCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

