/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the AccountLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountLimits{}

// AccountLimits struct for AccountLimits
type AccountLimits struct {
	ApiRateLimitPerMinute *int32 `json:"api_rate_limit_per_minute,omitempty"`
	ApiRateLimitPerHour *int32 `json:"api_rate_limit_per_hour,omitempty"`
	WebhookSupport *bool `json:"webhook_support,omitempty"`
}

// NewAccountLimits instantiates a new AccountLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountLimits() *AccountLimits {
	this := AccountLimits{}
	return &this
}

// NewAccountLimitsWithDefaults instantiates a new AccountLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountLimitsWithDefaults() *AccountLimits {
	this := AccountLimits{}
	return &this
}

// GetApiRateLimitPerMinute returns the ApiRateLimitPerMinute field value if set, zero value otherwise.
func (o *AccountLimits) GetApiRateLimitPerMinute() int32 {
	if o == nil || IsNil(o.ApiRateLimitPerMinute) {
		var ret int32
		return ret
	}
	return *o.ApiRateLimitPerMinute
}

// GetApiRateLimitPerMinuteOk returns a tuple with the ApiRateLimitPerMinute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetApiRateLimitPerMinuteOk() (*int32, bool) {
	if o == nil || IsNil(o.ApiRateLimitPerMinute) {
		return nil, false
	}
	return o.ApiRateLimitPerMinute, true
}

// HasApiRateLimitPerMinute returns a boolean if a field has been set.
func (o *AccountLimits) HasApiRateLimitPerMinute() bool {
	if o != nil && !IsNil(o.ApiRateLimitPerMinute) {
		return true
	}

	return false
}

// SetApiRateLimitPerMinute gets a reference to the given int32 and assigns it to the ApiRateLimitPerMinute field.
func (o *AccountLimits) SetApiRateLimitPerMinute(v int32) {
	o.ApiRateLimitPerMinute = &v
}

// GetApiRateLimitPerHour returns the ApiRateLimitPerHour field value if set, zero value otherwise.
func (o *AccountLimits) GetApiRateLimitPerHour() int32 {
	if o == nil || IsNil(o.ApiRateLimitPerHour) {
		var ret int32
		return ret
	}
	return *o.ApiRateLimitPerHour
}

// GetApiRateLimitPerHourOk returns a tuple with the ApiRateLimitPerHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetApiRateLimitPerHourOk() (*int32, bool) {
	if o == nil || IsNil(o.ApiRateLimitPerHour) {
		return nil, false
	}
	return o.ApiRateLimitPerHour, true
}

// HasApiRateLimitPerHour returns a boolean if a field has been set.
func (o *AccountLimits) HasApiRateLimitPerHour() bool {
	if o != nil && !IsNil(o.ApiRateLimitPerHour) {
		return true
	}

	return false
}

// SetApiRateLimitPerHour gets a reference to the given int32 and assigns it to the ApiRateLimitPerHour field.
func (o *AccountLimits) SetApiRateLimitPerHour(v int32) {
	o.ApiRateLimitPerHour = &v
}

// GetWebhookSupport returns the WebhookSupport field value if set, zero value otherwise.
func (o *AccountLimits) GetWebhookSupport() bool {
	if o == nil || IsNil(o.WebhookSupport) {
		var ret bool
		return ret
	}
	return *o.WebhookSupport
}

// GetWebhookSupportOk returns a tuple with the WebhookSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetWebhookSupportOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhookSupport) {
		return nil, false
	}
	return o.WebhookSupport, true
}

// HasWebhookSupport returns a boolean if a field has been set.
func (o *AccountLimits) HasWebhookSupport() bool {
	if o != nil && !IsNil(o.WebhookSupport) {
		return true
	}

	return false
}

// SetWebhookSupport gets a reference to the given bool and assigns it to the WebhookSupport field.
func (o *AccountLimits) SetWebhookSupport(v bool) {
	o.WebhookSupport = &v
}

func (o AccountLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiRateLimitPerMinute) {
		toSerialize["api_rate_limit_per_minute"] = o.ApiRateLimitPerMinute
	}
	if !IsNil(o.ApiRateLimitPerHour) {
		toSerialize["api_rate_limit_per_hour"] = o.ApiRateLimitPerHour
	}
	if !IsNil(o.WebhookSupport) {
		toSerialize["webhook_support"] = o.WebhookSupport
	}
	return toSerialize, nil
}

type NullableAccountLimits struct {
	value *AccountLimits
	isSet bool
}

func (v NullableAccountLimits) Get() *AccountLimits {
	return v.value
}

func (v *NullableAccountLimits) Set(val *AccountLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountLimits(val *AccountLimits) *NullableAccountLimits {
	return &NullableAccountLimits{value: val, isSet: true}
}

func (v NullableAccountLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


