/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InlineObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject{}

// InlineObject struct for InlineObject
type InlineObject struct {
	Success interface{} `json:"success"`
	// Machine-readable code.
	Error string `json:"error"`
	// Human-readable description.
	Message string `json:"message"`
	ExistingTransaction *InlineObjectAllOfExistingTransaction `json:"existing_transaction,omitempty"`
}

type _InlineObject InlineObject

// NewInlineObject instantiates a new InlineObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject(success interface{}, error_ string, message string) *InlineObject {
	this := InlineObject{}
	this.Success = success
	this.Error = error_
	this.Message = message
	return &this
}

// NewInlineObjectWithDefaults instantiates a new InlineObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObjectWithDefaults() *InlineObject {
	this := InlineObject{}
	return &this
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *InlineObject) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *InlineObject) SetSuccess(v interface{}) {
	o.Success = v
}

// GetError returns the Error field value
func (o *InlineObject) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *InlineObject) SetError(v string) {
	o.Error = v
}

// GetMessage returns the Message field value
func (o *InlineObject) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InlineObject) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InlineObject) SetMessage(v string) {
	o.Message = v
}

// GetExistingTransaction returns the ExistingTransaction field value if set, zero value otherwise.
func (o *InlineObject) GetExistingTransaction() InlineObjectAllOfExistingTransaction {
	if o == nil || IsNil(o.ExistingTransaction) {
		var ret InlineObjectAllOfExistingTransaction
		return ret
	}
	return *o.ExistingTransaction
}

// GetExistingTransactionOk returns a tuple with the ExistingTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject) GetExistingTransactionOk() (*InlineObjectAllOfExistingTransaction, bool) {
	if o == nil || IsNil(o.ExistingTransaction) {
		return nil, false
	}
	return o.ExistingTransaction, true
}

// HasExistingTransaction returns a boolean if a field has been set.
func (o *InlineObject) HasExistingTransaction() bool {
	if o != nil && !IsNil(o.ExistingTransaction) {
		return true
	}

	return false
}

// SetExistingTransaction gets a reference to the given InlineObjectAllOfExistingTransaction and assigns it to the ExistingTransaction field.
func (o *InlineObject) SetExistingTransaction(v InlineObjectAllOfExistingTransaction) {
	o.ExistingTransaction = &v
}

func (o InlineObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	toSerialize["error"] = o.Error
	toSerialize["message"] = o.Message
	if !IsNil(o.ExistingTransaction) {
		toSerialize["existing_transaction"] = o.ExistingTransaction
	}
	return toSerialize, nil
}

func (o *InlineObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"error",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInlineObject := _InlineObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInlineObject)

	if err != nil {
		return err
	}

	*o = InlineObject(varInlineObject)

	return err
}

type NullableInlineObject struct {
	value *InlineObject
	isSet bool
}

func (v NullableInlineObject) Get() *InlineObject {
	return v.value
}

func (v *NullableInlineObject) Set(val *InlineObject) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject(val *InlineObject) *NullableInlineObject {
	return &NullableInlineObject{value: val, isSet: true}
}

func (v NullableInlineObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


