/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"time"
)

// checks if the AccountPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountPlan{}

// AccountPlan struct for AccountPlan
type AccountPlan struct {
	Tier *PlanTier `json:"tier,omitempty"`
	BillingCycle *string `json:"billing_cycle,omitempty"`
	AutoRenewal *bool `json:"auto_renewal,omitempty"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
}

// NewAccountPlan instantiates a new AccountPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountPlan() *AccountPlan {
	this := AccountPlan{}
	return &this
}

// NewAccountPlanWithDefaults instantiates a new AccountPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountPlanWithDefaults() *AccountPlan {
	this := AccountPlan{}
	return &this
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *AccountPlan) GetTier() PlanTier {
	if o == nil || IsNil(o.Tier) {
		var ret PlanTier
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetTierOk() (*PlanTier, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *AccountPlan) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given PlanTier and assigns it to the Tier field.
func (o *AccountPlan) SetTier(v PlanTier) {
	o.Tier = &v
}

// GetBillingCycle returns the BillingCycle field value if set, zero value otherwise.
func (o *AccountPlan) GetBillingCycle() string {
	if o == nil || IsNil(o.BillingCycle) {
		var ret string
		return ret
	}
	return *o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetBillingCycleOk() (*string, bool) {
	if o == nil || IsNil(o.BillingCycle) {
		return nil, false
	}
	return o.BillingCycle, true
}

// HasBillingCycle returns a boolean if a field has been set.
func (o *AccountPlan) HasBillingCycle() bool {
	if o != nil && !IsNil(o.BillingCycle) {
		return true
	}

	return false
}

// SetBillingCycle gets a reference to the given string and assigns it to the BillingCycle field.
func (o *AccountPlan) SetBillingCycle(v string) {
	o.BillingCycle = &v
}

// GetAutoRenewal returns the AutoRenewal field value if set, zero value otherwise.
func (o *AccountPlan) GetAutoRenewal() bool {
	if o == nil || IsNil(o.AutoRenewal) {
		var ret bool
		return ret
	}
	return *o.AutoRenewal
}

// GetAutoRenewalOk returns a tuple with the AutoRenewal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountPlan) GetAutoRenewalOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoRenewal) {
		return nil, false
	}
	return o.AutoRenewal, true
}

// HasAutoRenewal returns a boolean if a field has been set.
func (o *AccountPlan) HasAutoRenewal() bool {
	if o != nil && !IsNil(o.AutoRenewal) {
		return true
	}

	return false
}

// SetAutoRenewal gets a reference to the given bool and assigns it to the AutoRenewal field.
func (o *AccountPlan) SetAutoRenewal(v bool) {
	o.AutoRenewal = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountPlan) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountPlan) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *AccountPlan) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *AccountPlan) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *AccountPlan) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *AccountPlan) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o AccountPlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.BillingCycle) {
		toSerialize["billing_cycle"] = o.BillingCycle
	}
	if !IsNil(o.AutoRenewal) {
		toSerialize["auto_renewal"] = o.AutoRenewal
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	return toSerialize, nil
}

type NullableAccountPlan struct {
	value *AccountPlan
	isSet bool
}

func (v NullableAccountPlan) Get() *AccountPlan {
	return v.value
}

func (v *NullableAccountPlan) Set(val *AccountPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountPlan(val *AccountPlan) *NullableAccountPlan {
	return &NullableAccountPlan{value: val, isSet: true}
}

func (v NullableAccountPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


