/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
)

// checks if the AccountUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountUsage{}

// AccountUsage struct for AccountUsage
type AccountUsage struct {
	MonthlyTransactionsUsed *int32 `json:"monthly_transactions_used,omitempty"`
	// null = unlimited.
	MonthlyTransactionLimit NullableInt32 `json:"monthly_transaction_limit,omitempty"`
	OverageCostPerTx *float32 `json:"overage_cost_per_tx,omitempty"`
}

// NewAccountUsage instantiates a new AccountUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountUsage() *AccountUsage {
	this := AccountUsage{}
	return &this
}

// NewAccountUsageWithDefaults instantiates a new AccountUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountUsageWithDefaults() *AccountUsage {
	this := AccountUsage{}
	return &this
}

// GetMonthlyTransactionsUsed returns the MonthlyTransactionsUsed field value if set, zero value otherwise.
func (o *AccountUsage) GetMonthlyTransactionsUsed() int32 {
	if o == nil || IsNil(o.MonthlyTransactionsUsed) {
		var ret int32
		return ret
	}
	return *o.MonthlyTransactionsUsed
}

// GetMonthlyTransactionsUsedOk returns a tuple with the MonthlyTransactionsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountUsage) GetMonthlyTransactionsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyTransactionsUsed) {
		return nil, false
	}
	return o.MonthlyTransactionsUsed, true
}

// HasMonthlyTransactionsUsed returns a boolean if a field has been set.
func (o *AccountUsage) HasMonthlyTransactionsUsed() bool {
	if o != nil && !IsNil(o.MonthlyTransactionsUsed) {
		return true
	}

	return false
}

// SetMonthlyTransactionsUsed gets a reference to the given int32 and assigns it to the MonthlyTransactionsUsed field.
func (o *AccountUsage) SetMonthlyTransactionsUsed(v int32) {
	o.MonthlyTransactionsUsed = &v
}

// GetMonthlyTransactionLimit returns the MonthlyTransactionLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountUsage) GetMonthlyTransactionLimit() int32 {
	if o == nil || IsNil(o.MonthlyTransactionLimit.Get()) {
		var ret int32
		return ret
	}
	return *o.MonthlyTransactionLimit.Get()
}

// GetMonthlyTransactionLimitOk returns a tuple with the MonthlyTransactionLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountUsage) GetMonthlyTransactionLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyTransactionLimit.Get(), o.MonthlyTransactionLimit.IsSet()
}

// HasMonthlyTransactionLimit returns a boolean if a field has been set.
func (o *AccountUsage) HasMonthlyTransactionLimit() bool {
	if o != nil && o.MonthlyTransactionLimit.IsSet() {
		return true
	}

	return false
}

// SetMonthlyTransactionLimit gets a reference to the given NullableInt32 and assigns it to the MonthlyTransactionLimit field.
func (o *AccountUsage) SetMonthlyTransactionLimit(v int32) {
	o.MonthlyTransactionLimit.Set(&v)
}
// SetMonthlyTransactionLimitNil sets the value for MonthlyTransactionLimit to be an explicit nil
func (o *AccountUsage) SetMonthlyTransactionLimitNil() {
	o.MonthlyTransactionLimit.Set(nil)
}

// UnsetMonthlyTransactionLimit ensures that no value is present for MonthlyTransactionLimit, not even an explicit nil
func (o *AccountUsage) UnsetMonthlyTransactionLimit() {
	o.MonthlyTransactionLimit.Unset()
}

// GetOverageCostPerTx returns the OverageCostPerTx field value if set, zero value otherwise.
func (o *AccountUsage) GetOverageCostPerTx() float32 {
	if o == nil || IsNil(o.OverageCostPerTx) {
		var ret float32
		return ret
	}
	return *o.OverageCostPerTx
}

// GetOverageCostPerTxOk returns a tuple with the OverageCostPerTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountUsage) GetOverageCostPerTxOk() (*float32, bool) {
	if o == nil || IsNil(o.OverageCostPerTx) {
		return nil, false
	}
	return o.OverageCostPerTx, true
}

// HasOverageCostPerTx returns a boolean if a field has been set.
func (o *AccountUsage) HasOverageCostPerTx() bool {
	if o != nil && !IsNil(o.OverageCostPerTx) {
		return true
	}

	return false
}

// SetOverageCostPerTx gets a reference to the given float32 and assigns it to the OverageCostPerTx field.
func (o *AccountUsage) SetOverageCostPerTx(v float32) {
	o.OverageCostPerTx = &v
}

func (o AccountUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MonthlyTransactionsUsed) {
		toSerialize["monthly_transactions_used"] = o.MonthlyTransactionsUsed
	}
	if o.MonthlyTransactionLimit.IsSet() {
		toSerialize["monthly_transaction_limit"] = o.MonthlyTransactionLimit.Get()
	}
	if !IsNil(o.OverageCostPerTx) {
		toSerialize["overage_cost_per_tx"] = o.OverageCostPerTx
	}
	return toSerialize, nil
}

type NullableAccountUsage struct {
	value *AccountUsage
	isSet bool
}

func (v NullableAccountUsage) Get() *AccountUsage {
	return v.value
}

func (v *NullableAccountUsage) Set(val *AccountUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountUsage(val *AccountUsage) *NullableAccountUsage {
	return &NullableAccountUsage{value: val, isSet: true}
}

func (v NullableAccountUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


