/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDetailedTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDetailedTransactionRequest{}

// CreateDetailedTransactionRequest struct for CreateDetailedTransactionRequest
type CreateDetailedTransactionRequest struct {
	Crypto CryptoSymbol `json:"crypto"`
	CurrencyFiat *FiatCurrency `json:"currency_fiat,omitempty"`
	Items []LineItem `json:"items"`
	OrderId string `json:"order_id"`
	// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
	Metadata map[string]string `json:"metadata,omitempty"`
	CustomerEmail NullableString `json:"customer_email,omitempty"`
	SuccessUrl NullableString `json:"success_url,omitempty"`
	CancelUrl NullableString `json:"cancel_url,omitempty"`
}

type _CreateDetailedTransactionRequest CreateDetailedTransactionRequest

// NewCreateDetailedTransactionRequest instantiates a new CreateDetailedTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDetailedTransactionRequest(crypto CryptoSymbol, items []LineItem, orderId string) *CreateDetailedTransactionRequest {
	this := CreateDetailedTransactionRequest{}
	this.Crypto = crypto
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	this.Items = items
	this.OrderId = orderId
	return &this
}

// NewCreateDetailedTransactionRequestWithDefaults instantiates a new CreateDetailedTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDetailedTransactionRequestWithDefaults() *CreateDetailedTransactionRequest {
	this := CreateDetailedTransactionRequest{}
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	return &this
}

// GetCrypto returns the Crypto field value
func (o *CreateDetailedTransactionRequest) GetCrypto() CryptoSymbol {
	if o == nil {
		var ret CryptoSymbol
		return ret
	}

	return o.Crypto
}

// GetCryptoOk returns a tuple with the Crypto field value
// and a boolean to check if the value has been set.
func (o *CreateDetailedTransactionRequest) GetCryptoOk() (*CryptoSymbol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Crypto, true
}

// SetCrypto sets field value
func (o *CreateDetailedTransactionRequest) SetCrypto(v CryptoSymbol) {
	o.Crypto = v
}

// GetCurrencyFiat returns the CurrencyFiat field value if set, zero value otherwise.
func (o *CreateDetailedTransactionRequest) GetCurrencyFiat() FiatCurrency {
	if o == nil || IsNil(o.CurrencyFiat) {
		var ret FiatCurrency
		return ret
	}
	return *o.CurrencyFiat
}

// GetCurrencyFiatOk returns a tuple with the CurrencyFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDetailedTransactionRequest) GetCurrencyFiatOk() (*FiatCurrency, bool) {
	if o == nil || IsNil(o.CurrencyFiat) {
		return nil, false
	}
	return o.CurrencyFiat, true
}

// HasCurrencyFiat returns a boolean if a field has been set.
func (o *CreateDetailedTransactionRequest) HasCurrencyFiat() bool {
	if o != nil && !IsNil(o.CurrencyFiat) {
		return true
	}

	return false
}

// SetCurrencyFiat gets a reference to the given FiatCurrency and assigns it to the CurrencyFiat field.
func (o *CreateDetailedTransactionRequest) SetCurrencyFiat(v FiatCurrency) {
	o.CurrencyFiat = &v
}

// GetItems returns the Items field value
func (o *CreateDetailedTransactionRequest) GetItems() []LineItem {
	if o == nil {
		var ret []LineItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CreateDetailedTransactionRequest) GetItemsOk() ([]LineItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CreateDetailedTransactionRequest) SetItems(v []LineItem) {
	o.Items = v
}

// GetOrderId returns the OrderId field value
func (o *CreateDetailedTransactionRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CreateDetailedTransactionRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CreateDetailedTransactionRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateDetailedTransactionRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDetailedTransactionRequest) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateDetailedTransactionRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreateDetailedTransactionRequest) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDetailedTransactionRequest) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerEmail.Get()
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDetailedTransactionRequest) GetCustomerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerEmail.Get(), o.CustomerEmail.IsSet()
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *CreateDetailedTransactionRequest) HasCustomerEmail() bool {
	if o != nil && o.CustomerEmail.IsSet() {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given NullableString and assigns it to the CustomerEmail field.
func (o *CreateDetailedTransactionRequest) SetCustomerEmail(v string) {
	o.CustomerEmail.Set(&v)
}
// SetCustomerEmailNil sets the value for CustomerEmail to be an explicit nil
func (o *CreateDetailedTransactionRequest) SetCustomerEmailNil() {
	o.CustomerEmail.Set(nil)
}

// UnsetCustomerEmail ensures that no value is present for CustomerEmail, not even an explicit nil
func (o *CreateDetailedTransactionRequest) UnsetCustomerEmail() {
	o.CustomerEmail.Unset()
}

// GetSuccessUrl returns the SuccessUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDetailedTransactionRequest) GetSuccessUrl() string {
	if o == nil || IsNil(o.SuccessUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SuccessUrl.Get()
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDetailedTransactionRequest) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuccessUrl.Get(), o.SuccessUrl.IsSet()
}

// HasSuccessUrl returns a boolean if a field has been set.
func (o *CreateDetailedTransactionRequest) HasSuccessUrl() bool {
	if o != nil && o.SuccessUrl.IsSet() {
		return true
	}

	return false
}

// SetSuccessUrl gets a reference to the given NullableString and assigns it to the SuccessUrl field.
func (o *CreateDetailedTransactionRequest) SetSuccessUrl(v string) {
	o.SuccessUrl.Set(&v)
}
// SetSuccessUrlNil sets the value for SuccessUrl to be an explicit nil
func (o *CreateDetailedTransactionRequest) SetSuccessUrlNil() {
	o.SuccessUrl.Set(nil)
}

// UnsetSuccessUrl ensures that no value is present for SuccessUrl, not even an explicit nil
func (o *CreateDetailedTransactionRequest) UnsetSuccessUrl() {
	o.SuccessUrl.Unset()
}

// GetCancelUrl returns the CancelUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateDetailedTransactionRequest) GetCancelUrl() string {
	if o == nil || IsNil(o.CancelUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CancelUrl.Get()
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDetailedTransactionRequest) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancelUrl.Get(), o.CancelUrl.IsSet()
}

// HasCancelUrl returns a boolean if a field has been set.
func (o *CreateDetailedTransactionRequest) HasCancelUrl() bool {
	if o != nil && o.CancelUrl.IsSet() {
		return true
	}

	return false
}

// SetCancelUrl gets a reference to the given NullableString and assigns it to the CancelUrl field.
func (o *CreateDetailedTransactionRequest) SetCancelUrl(v string) {
	o.CancelUrl.Set(&v)
}
// SetCancelUrlNil sets the value for CancelUrl to be an explicit nil
func (o *CreateDetailedTransactionRequest) SetCancelUrlNil() {
	o.CancelUrl.Set(nil)
}

// UnsetCancelUrl ensures that no value is present for CancelUrl, not even an explicit nil
func (o *CreateDetailedTransactionRequest) UnsetCancelUrl() {
	o.CancelUrl.Unset()
}

func (o CreateDetailedTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDetailedTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["crypto"] = o.Crypto
	if !IsNil(o.CurrencyFiat) {
		toSerialize["currency_fiat"] = o.CurrencyFiat
	}
	toSerialize["items"] = o.Items
	toSerialize["order_id"] = o.OrderId
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.CustomerEmail.IsSet() {
		toSerialize["customer_email"] = o.CustomerEmail.Get()
	}
	if o.SuccessUrl.IsSet() {
		toSerialize["success_url"] = o.SuccessUrl.Get()
	}
	if o.CancelUrl.IsSet() {
		toSerialize["cancel_url"] = o.CancelUrl.Get()
	}
	return toSerialize, nil
}

func (o *CreateDetailedTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"crypto",
		"items",
		"order_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDetailedTransactionRequest := _CreateDetailedTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDetailedTransactionRequest)

	if err != nil {
		return err
	}

	*o = CreateDetailedTransactionRequest(varCreateDetailedTransactionRequest)

	return err
}

type NullableCreateDetailedTransactionRequest struct {
	value *CreateDetailedTransactionRequest
	isSet bool
}

func (v NullableCreateDetailedTransactionRequest) Get() *CreateDetailedTransactionRequest {
	return v.value
}

func (v *NullableCreateDetailedTransactionRequest) Set(val *CreateDetailedTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDetailedTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDetailedTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDetailedTransactionRequest(val *CreateDetailedTransactionRequest) *NullableCreateDetailedTransactionRequest {
	return &NullableCreateDetailedTransactionRequest{value: val, isSet: true}
}

func (v NullableCreateDetailedTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDetailedTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


