/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
)

// checks if the GetStats200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStats200ResponseData{}

// GetStats200ResponseData struct for GetStats200ResponseData
type GetStats200ResponseData struct {
	TotalTransactions *int32 `json:"total_transactions,omitempty"`
	MonthlyTransactions *int32 `json:"monthly_transactions,omitempty"`
	TotalVolumeFiat *float32 `json:"total_volume_fiat,omitempty"`
	UniqueCustomers *int32 `json:"unique_customers,omitempty"`
}

// NewGetStats200ResponseData instantiates a new GetStats200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStats200ResponseData() *GetStats200ResponseData {
	this := GetStats200ResponseData{}
	return &this
}

// NewGetStats200ResponseDataWithDefaults instantiates a new GetStats200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStats200ResponseDataWithDefaults() *GetStats200ResponseData {
	this := GetStats200ResponseData{}
	return &this
}

// GetTotalTransactions returns the TotalTransactions field value if set, zero value otherwise.
func (o *GetStats200ResponseData) GetTotalTransactions() int32 {
	if o == nil || IsNil(o.TotalTransactions) {
		var ret int32
		return ret
	}
	return *o.TotalTransactions
}

// GetTotalTransactionsOk returns a tuple with the TotalTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStats200ResponseData) GetTotalTransactionsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTransactions) {
		return nil, false
	}
	return o.TotalTransactions, true
}

// HasTotalTransactions returns a boolean if a field has been set.
func (o *GetStats200ResponseData) HasTotalTransactions() bool {
	if o != nil && !IsNil(o.TotalTransactions) {
		return true
	}

	return false
}

// SetTotalTransactions gets a reference to the given int32 and assigns it to the TotalTransactions field.
func (o *GetStats200ResponseData) SetTotalTransactions(v int32) {
	o.TotalTransactions = &v
}

// GetMonthlyTransactions returns the MonthlyTransactions field value if set, zero value otherwise.
func (o *GetStats200ResponseData) GetMonthlyTransactions() int32 {
	if o == nil || IsNil(o.MonthlyTransactions) {
		var ret int32
		return ret
	}
	return *o.MonthlyTransactions
}

// GetMonthlyTransactionsOk returns a tuple with the MonthlyTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStats200ResponseData) GetMonthlyTransactionsOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyTransactions) {
		return nil, false
	}
	return o.MonthlyTransactions, true
}

// HasMonthlyTransactions returns a boolean if a field has been set.
func (o *GetStats200ResponseData) HasMonthlyTransactions() bool {
	if o != nil && !IsNil(o.MonthlyTransactions) {
		return true
	}

	return false
}

// SetMonthlyTransactions gets a reference to the given int32 and assigns it to the MonthlyTransactions field.
func (o *GetStats200ResponseData) SetMonthlyTransactions(v int32) {
	o.MonthlyTransactions = &v
}

// GetTotalVolumeFiat returns the TotalVolumeFiat field value if set, zero value otherwise.
func (o *GetStats200ResponseData) GetTotalVolumeFiat() float32 {
	if o == nil || IsNil(o.TotalVolumeFiat) {
		var ret float32
		return ret
	}
	return *o.TotalVolumeFiat
}

// GetTotalVolumeFiatOk returns a tuple with the TotalVolumeFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStats200ResponseData) GetTotalVolumeFiatOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalVolumeFiat) {
		return nil, false
	}
	return o.TotalVolumeFiat, true
}

// HasTotalVolumeFiat returns a boolean if a field has been set.
func (o *GetStats200ResponseData) HasTotalVolumeFiat() bool {
	if o != nil && !IsNil(o.TotalVolumeFiat) {
		return true
	}

	return false
}

// SetTotalVolumeFiat gets a reference to the given float32 and assigns it to the TotalVolumeFiat field.
func (o *GetStats200ResponseData) SetTotalVolumeFiat(v float32) {
	o.TotalVolumeFiat = &v
}

// GetUniqueCustomers returns the UniqueCustomers field value if set, zero value otherwise.
func (o *GetStats200ResponseData) GetUniqueCustomers() int32 {
	if o == nil || IsNil(o.UniqueCustomers) {
		var ret int32
		return ret
	}
	return *o.UniqueCustomers
}

// GetUniqueCustomersOk returns a tuple with the UniqueCustomers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStats200ResponseData) GetUniqueCustomersOk() (*int32, bool) {
	if o == nil || IsNil(o.UniqueCustomers) {
		return nil, false
	}
	return o.UniqueCustomers, true
}

// HasUniqueCustomers returns a boolean if a field has been set.
func (o *GetStats200ResponseData) HasUniqueCustomers() bool {
	if o != nil && !IsNil(o.UniqueCustomers) {
		return true
	}

	return false
}

// SetUniqueCustomers gets a reference to the given int32 and assigns it to the UniqueCustomers field.
func (o *GetStats200ResponseData) SetUniqueCustomers(v int32) {
	o.UniqueCustomers = &v
}

func (o GetStats200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStats200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalTransactions) {
		toSerialize["total_transactions"] = o.TotalTransactions
	}
	if !IsNil(o.MonthlyTransactions) {
		toSerialize["monthly_transactions"] = o.MonthlyTransactions
	}
	if !IsNil(o.TotalVolumeFiat) {
		toSerialize["total_volume_fiat"] = o.TotalVolumeFiat
	}
	if !IsNil(o.UniqueCustomers) {
		toSerialize["unique_customers"] = o.UniqueCustomers
	}
	return toSerialize, nil
}

type NullableGetStats200ResponseData struct {
	value *GetStats200ResponseData
	isSet bool
}

func (v NullableGetStats200ResponseData) Get() *GetStats200ResponseData {
	return v.value
}

func (v *NullableGetStats200ResponseData) Set(val *GetStats200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStats200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStats200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStats200ResponseData(val *GetStats200ResponseData) *NullableGetStats200ResponseData {
	return &NullableGetStats200ResponseData{value: val, isSet: true}
}

func (v NullableGetStats200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStats200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


