/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListTransactions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTransactions200Response{}

// ListTransactions200Response struct for ListTransactions200Response
type ListTransactions200Response struct {
	Success interface{} `json:"success"`
	Data ListTransactions200ResponseData `json:"data"`
}

type _ListTransactions200Response ListTransactions200Response

// NewListTransactions200Response instantiates a new ListTransactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTransactions200Response(success interface{}, data ListTransactions200ResponseData) *ListTransactions200Response {
	this := ListTransactions200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewListTransactions200ResponseWithDefaults instantiates a new ListTransactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTransactions200ResponseWithDefaults() *ListTransactions200Response {
	this := ListTransactions200Response{}
	return &this
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ListTransactions200Response) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTransactions200Response) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ListTransactions200Response) SetSuccess(v interface{}) {
	o.Success = v
}

// GetData returns the Data field value
func (o *ListTransactions200Response) GetData() ListTransactions200ResponseData {
	if o == nil {
		var ret ListTransactions200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListTransactions200Response) GetDataOk() (*ListTransactions200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListTransactions200Response) SetData(v ListTransactions200ResponseData) {
	o.Data = v
}

func (o ListTransactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTransactions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListTransactions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTransactions200Response := _ListTransactions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListTransactions200Response)

	if err != nil {
		return err
	}

	*o = ListTransactions200Response(varListTransactions200Response)

	return err
}

type NullableListTransactions200Response struct {
	value *ListTransactions200Response
	isSet bool
}

func (v NullableListTransactions200Response) Get() *ListTransactions200Response {
	return v.value
}

func (v *NullableListTransactions200Response) Set(val *ListTransactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTransactions200Response(val *ListTransactions200Response) *NullableListTransactions200Response {
	return &NullableListTransactions200Response{value: val, isSet: true}
}

func (v NullableListTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


