/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the ListPlans200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPlans200ResponseData{}

// ListPlans200ResponseData struct for ListPlans200ResponseData
type ListPlans200ResponseData struct {
	Plans []Plan `json:"plans,omitempty"`
	BillingCycles []string `json:"billing_cycles,omitempty"`
}

// NewListPlans200ResponseData instantiates a new ListPlans200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlans200ResponseData() *ListPlans200ResponseData {
	this := ListPlans200ResponseData{}
	return &this
}

// NewListPlans200ResponseDataWithDefaults instantiates a new ListPlans200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlans200ResponseDataWithDefaults() *ListPlans200ResponseData {
	this := ListPlans200ResponseData{}
	return &this
}

// GetPlans returns the Plans field value if set, zero value otherwise.
func (o *ListPlans200ResponseData) GetPlans() []Plan {
	if o == nil || IsNil(o.Plans) {
		var ret []Plan
		return ret
	}
	return o.Plans
}

// GetPlansOk returns a tuple with the Plans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlans200ResponseData) GetPlansOk() ([]Plan, bool) {
	if o == nil || IsNil(o.Plans) {
		return nil, false
	}
	return o.Plans, true
}

// HasPlans returns a boolean if a field has been set.
func (o *ListPlans200ResponseData) HasPlans() bool {
	if o != nil && !IsNil(o.Plans) {
		return true
	}

	return false
}

// SetPlans gets a reference to the given []Plan and assigns it to the Plans field.
func (o *ListPlans200ResponseData) SetPlans(v []Plan) {
	o.Plans = v
}

// GetBillingCycles returns the BillingCycles field value if set, zero value otherwise.
func (o *ListPlans200ResponseData) GetBillingCycles() []string {
	if o == nil || IsNil(o.BillingCycles) {
		var ret []string
		return ret
	}
	return o.BillingCycles
}

// GetBillingCyclesOk returns a tuple with the BillingCycles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlans200ResponseData) GetBillingCyclesOk() ([]string, bool) {
	if o == nil || IsNil(o.BillingCycles) {
		return nil, false
	}
	return o.BillingCycles, true
}

// HasBillingCycles returns a boolean if a field has been set.
func (o *ListPlans200ResponseData) HasBillingCycles() bool {
	if o != nil && !IsNil(o.BillingCycles) {
		return true
	}

	return false
}

// SetBillingCycles gets a reference to the given []string and assigns it to the BillingCycles field.
func (o *ListPlans200ResponseData) SetBillingCycles(v []string) {
	o.BillingCycles = v
}

func (o ListPlans200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPlans200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plans) {
		toSerialize["plans"] = o.Plans
	}
	if !IsNil(o.BillingCycles) {
		toSerialize["billing_cycles"] = o.BillingCycles
	}
	return toSerialize, nil
}

type NullableListPlans200ResponseData struct {
	value *ListPlans200ResponseData
	isSet bool
}

func (v NullableListPlans200ResponseData) Get() *ListPlans200ResponseData {
	return v.value
}

func (v *NullableListPlans200ResponseData) Set(val *ListPlans200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlans200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlans200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlans200ResponseData(val *ListPlans200ResponseData) *NullableListPlans200ResponseData {
	return &NullableListPlans200ResponseData{value: val, isSet: true}
}

func (v NullableListPlans200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPlans200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


