/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBillingCheckoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBillingCheckoutRequest{}

// CreateBillingCheckoutRequest struct for CreateBillingCheckoutRequest
type CreateBillingCheckoutRequest struct {
	Tier PlanTier `json:"tier"`
	BillingMonths *int32 `json:"billing_months,omitempty"`
	PaymentMethod *string `json:"payment_method,omitempty"`
}

type _CreateBillingCheckoutRequest CreateBillingCheckoutRequest

// NewCreateBillingCheckoutRequest instantiates a new CreateBillingCheckoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBillingCheckoutRequest(tier PlanTier) *CreateBillingCheckoutRequest {
	this := CreateBillingCheckoutRequest{}
	this.Tier = tier
	var billingMonths int32 = 1
	this.BillingMonths = &billingMonths
	var paymentMethod string = "crypto"
	this.PaymentMethod = &paymentMethod
	return &this
}

// NewCreateBillingCheckoutRequestWithDefaults instantiates a new CreateBillingCheckoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBillingCheckoutRequestWithDefaults() *CreateBillingCheckoutRequest {
	this := CreateBillingCheckoutRequest{}
	var billingMonths int32 = 1
	this.BillingMonths = &billingMonths
	var paymentMethod string = "crypto"
	this.PaymentMethod = &paymentMethod
	return &this
}

// GetTier returns the Tier field value
func (o *CreateBillingCheckoutRequest) GetTier() PlanTier {
	if o == nil {
		var ret PlanTier
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *CreateBillingCheckoutRequest) GetTierOk() (*PlanTier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *CreateBillingCheckoutRequest) SetTier(v PlanTier) {
	o.Tier = v
}

// GetBillingMonths returns the BillingMonths field value if set, zero value otherwise.
func (o *CreateBillingCheckoutRequest) GetBillingMonths() int32 {
	if o == nil || IsNil(o.BillingMonths) {
		var ret int32
		return ret
	}
	return *o.BillingMonths
}

// GetBillingMonthsOk returns a tuple with the BillingMonths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBillingCheckoutRequest) GetBillingMonthsOk() (*int32, bool) {
	if o == nil || IsNil(o.BillingMonths) {
		return nil, false
	}
	return o.BillingMonths, true
}

// HasBillingMonths returns a boolean if a field has been set.
func (o *CreateBillingCheckoutRequest) HasBillingMonths() bool {
	if o != nil && !IsNil(o.BillingMonths) {
		return true
	}

	return false
}

// SetBillingMonths gets a reference to the given int32 and assigns it to the BillingMonths field.
func (o *CreateBillingCheckoutRequest) SetBillingMonths(v int32) {
	o.BillingMonths = &v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *CreateBillingCheckoutRequest) GetPaymentMethod() string {
	if o == nil || IsNil(o.PaymentMethod) {
		var ret string
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBillingCheckoutRequest) GetPaymentMethodOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethod) {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *CreateBillingCheckoutRequest) HasPaymentMethod() bool {
	if o != nil && !IsNil(o.PaymentMethod) {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given string and assigns it to the PaymentMethod field.
func (o *CreateBillingCheckoutRequest) SetPaymentMethod(v string) {
	o.PaymentMethod = &v
}

func (o CreateBillingCheckoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBillingCheckoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tier"] = o.Tier
	if !IsNil(o.BillingMonths) {
		toSerialize["billing_months"] = o.BillingMonths
	}
	if !IsNil(o.PaymentMethod) {
		toSerialize["payment_method"] = o.PaymentMethod
	}
	return toSerialize, nil
}

func (o *CreateBillingCheckoutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBillingCheckoutRequest := _CreateBillingCheckoutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBillingCheckoutRequest)

	if err != nil {
		return err
	}

	*o = CreateBillingCheckoutRequest(varCreateBillingCheckoutRequest)

	return err
}

type NullableCreateBillingCheckoutRequest struct {
	value *CreateBillingCheckoutRequest
	isSet bool
}

func (v NullableCreateBillingCheckoutRequest) Get() *CreateBillingCheckoutRequest {
	return v.value
}

func (v *NullableCreateBillingCheckoutRequest) Set(val *CreateBillingCheckoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBillingCheckoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBillingCheckoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBillingCheckoutRequest(val *CreateBillingCheckoutRequest) *NullableCreateBillingCheckoutRequest {
	return &NullableCreateBillingCheckoutRequest{value: val, isSet: true}
}

func (v NullableCreateBillingCheckoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBillingCheckoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


