/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"time"
)

// checks if the PaymentSplit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentSplit{}

// PaymentSplit One on-chain payment toward the transaction.
type PaymentSplit struct {
	// On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id).
	Txid *string `json:"txid,omitempty"`
	AmountCrypto *float32 `json:"amount_crypto,omitempty"`
	Confirmations *int32 `json:"confirmations,omitempty"`
	Status *string `json:"status,omitempty"`
	DetectedAt *time.Time `json:"detected_at,omitempty"`
	ConfirmedAt NullableTime `json:"confirmed_at,omitempty"`
}

// NewPaymentSplit instantiates a new PaymentSplit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentSplit() *PaymentSplit {
	this := PaymentSplit{}
	return &this
}

// NewPaymentSplitWithDefaults instantiates a new PaymentSplit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentSplitWithDefaults() *PaymentSplit {
	this := PaymentSplit{}
	return &this
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *PaymentSplit) GetTxid() string {
	if o == nil || IsNil(o.Txid) {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSplit) GetTxidOk() (*string, bool) {
	if o == nil || IsNil(o.Txid) {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *PaymentSplit) HasTxid() bool {
	if o != nil && !IsNil(o.Txid) {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *PaymentSplit) SetTxid(v string) {
	o.Txid = &v
}

// GetAmountCrypto returns the AmountCrypto field value if set, zero value otherwise.
func (o *PaymentSplit) GetAmountCrypto() float32 {
	if o == nil || IsNil(o.AmountCrypto) {
		var ret float32
		return ret
	}
	return *o.AmountCrypto
}

// GetAmountCryptoOk returns a tuple with the AmountCrypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSplit) GetAmountCryptoOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountCrypto) {
		return nil, false
	}
	return o.AmountCrypto, true
}

// HasAmountCrypto returns a boolean if a field has been set.
func (o *PaymentSplit) HasAmountCrypto() bool {
	if o != nil && !IsNil(o.AmountCrypto) {
		return true
	}

	return false
}

// SetAmountCrypto gets a reference to the given float32 and assigns it to the AmountCrypto field.
func (o *PaymentSplit) SetAmountCrypto(v float32) {
	o.AmountCrypto = &v
}

// GetConfirmations returns the Confirmations field value if set, zero value otherwise.
func (o *PaymentSplit) GetConfirmations() int32 {
	if o == nil || IsNil(o.Confirmations) {
		var ret int32
		return ret
	}
	return *o.Confirmations
}

// GetConfirmationsOk returns a tuple with the Confirmations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSplit) GetConfirmationsOk() (*int32, bool) {
	if o == nil || IsNil(o.Confirmations) {
		return nil, false
	}
	return o.Confirmations, true
}

// HasConfirmations returns a boolean if a field has been set.
func (o *PaymentSplit) HasConfirmations() bool {
	if o != nil && !IsNil(o.Confirmations) {
		return true
	}

	return false
}

// SetConfirmations gets a reference to the given int32 and assigns it to the Confirmations field.
func (o *PaymentSplit) SetConfirmations(v int32) {
	o.Confirmations = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PaymentSplit) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSplit) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentSplit) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PaymentSplit) SetStatus(v string) {
	o.Status = &v
}

// GetDetectedAt returns the DetectedAt field value if set, zero value otherwise.
func (o *PaymentSplit) GetDetectedAt() time.Time {
	if o == nil || IsNil(o.DetectedAt) {
		var ret time.Time
		return ret
	}
	return *o.DetectedAt
}

// GetDetectedAtOk returns a tuple with the DetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSplit) GetDetectedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DetectedAt) {
		return nil, false
	}
	return o.DetectedAt, true
}

// HasDetectedAt returns a boolean if a field has been set.
func (o *PaymentSplit) HasDetectedAt() bool {
	if o != nil && !IsNil(o.DetectedAt) {
		return true
	}

	return false
}

// SetDetectedAt gets a reference to the given time.Time and assigns it to the DetectedAt field.
func (o *PaymentSplit) SetDetectedAt(v time.Time) {
	o.DetectedAt = &v
}

// GetConfirmedAt returns the ConfirmedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentSplit) GetConfirmedAt() time.Time {
	if o == nil || IsNil(o.ConfirmedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmedAt.Get()
}

// GetConfirmedAtOk returns a tuple with the ConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentSplit) GetConfirmedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfirmedAt.Get(), o.ConfirmedAt.IsSet()
}

// HasConfirmedAt returns a boolean if a field has been set.
func (o *PaymentSplit) HasConfirmedAt() bool {
	if o != nil && o.ConfirmedAt.IsSet() {
		return true
	}

	return false
}

// SetConfirmedAt gets a reference to the given NullableTime and assigns it to the ConfirmedAt field.
func (o *PaymentSplit) SetConfirmedAt(v time.Time) {
	o.ConfirmedAt.Set(&v)
}
// SetConfirmedAtNil sets the value for ConfirmedAt to be an explicit nil
func (o *PaymentSplit) SetConfirmedAtNil() {
	o.ConfirmedAt.Set(nil)
}

// UnsetConfirmedAt ensures that no value is present for ConfirmedAt, not even an explicit nil
func (o *PaymentSplit) UnsetConfirmedAt() {
	o.ConfirmedAt.Unset()
}

func (o PaymentSplit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentSplit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Txid) {
		toSerialize["txid"] = o.Txid
	}
	if !IsNil(o.AmountCrypto) {
		toSerialize["amount_crypto"] = o.AmountCrypto
	}
	if !IsNil(o.Confirmations) {
		toSerialize["confirmations"] = o.Confirmations
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DetectedAt) {
		toSerialize["detected_at"] = o.DetectedAt
	}
	if o.ConfirmedAt.IsSet() {
		toSerialize["confirmed_at"] = o.ConfirmedAt.Get()
	}
	return toSerialize, nil
}

type NullablePaymentSplit struct {
	value *PaymentSplit
	isSet bool
}

func (v NullablePaymentSplit) Get() *PaymentSplit {
	return v.value
}

func (v *NullablePaymentSplit) Set(val *PaymentSplit) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentSplit) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentSplit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentSplit(val *PaymentSplit) *NullablePaymentSplit {
	return &NullablePaymentSplit{value: val, isSet: true}
}

func (v NullablePaymentSplit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentSplit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


