/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPayload{}

// WebhookPayload Payment-event payload. AMOUNTS ARE STRINGS (e.g. \"100.00\", \"0.00109462\") to preserve decimal precision — parse before arithmetic. 
type WebhookPayload struct {
	Event string `json:"event"`
	Timestamp time.Time `json:"timestamp"`
	TransactionId string `json:"transaction_id"`
	Status TransactionStatus `json:"status"`
	CurrencyCrypto *CryptoSymbol `json:"currency_crypto,omitempty"`
	CurrencyFiat *FiatCurrency `json:"currency_fiat,omitempty"`
	// Decimal string.
	AmountFiat *string `json:"amount_fiat,omitempty"`
	// Decimal string.
	AmountUsd *string `json:"amount_usd,omitempty"`
	// Decimal string.
	AmountCrypto *string `json:"amount_crypto,omitempty"`
	OrderId NullableString `json:"order_id,omitempty"`
	// Present on completed/overpaid.
	ReceiptUrl NullableString `json:"receipt_url,omitempty"`
	// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
	Metadata map[string]string `json:"metadata,omitempty"`
}

type _WebhookPayload WebhookPayload

// NewWebhookPayload instantiates a new WebhookPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPayload(event string, timestamp time.Time, transactionId string, status TransactionStatus) *WebhookPayload {
	this := WebhookPayload{}
	this.Event = event
	this.Timestamp = timestamp
	this.TransactionId = transactionId
	this.Status = status
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	return &this
}

// NewWebhookPayloadWithDefaults instantiates a new WebhookPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPayloadWithDefaults() *WebhookPayload {
	this := WebhookPayload{}
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = &currencyFiat
	return &this
}

// GetEvent returns the Event field value
func (o *WebhookPayload) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebhookPayload) SetEvent(v string) {
	o.Event = v
}

// GetTimestamp returns the Timestamp field value
func (o *WebhookPayload) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WebhookPayload) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetTransactionId returns the TransactionId field value
func (o *WebhookPayload) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *WebhookPayload) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetStatus returns the Status field value
func (o *WebhookPayload) GetStatus() TransactionStatus {
	if o == nil {
		var ret TransactionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetStatusOk() (*TransactionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookPayload) SetStatus(v TransactionStatus) {
	o.Status = v
}

// GetCurrencyCrypto returns the CurrencyCrypto field value if set, zero value otherwise.
func (o *WebhookPayload) GetCurrencyCrypto() CryptoSymbol {
	if o == nil || IsNil(o.CurrencyCrypto) {
		var ret CryptoSymbol
		return ret
	}
	return *o.CurrencyCrypto
}

// GetCurrencyCryptoOk returns a tuple with the CurrencyCrypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetCurrencyCryptoOk() (*CryptoSymbol, bool) {
	if o == nil || IsNil(o.CurrencyCrypto) {
		return nil, false
	}
	return o.CurrencyCrypto, true
}

// HasCurrencyCrypto returns a boolean if a field has been set.
func (o *WebhookPayload) HasCurrencyCrypto() bool {
	if o != nil && !IsNil(o.CurrencyCrypto) {
		return true
	}

	return false
}

// SetCurrencyCrypto gets a reference to the given CryptoSymbol and assigns it to the CurrencyCrypto field.
func (o *WebhookPayload) SetCurrencyCrypto(v CryptoSymbol) {
	o.CurrencyCrypto = &v
}

// GetCurrencyFiat returns the CurrencyFiat field value if set, zero value otherwise.
func (o *WebhookPayload) GetCurrencyFiat() FiatCurrency {
	if o == nil || IsNil(o.CurrencyFiat) {
		var ret FiatCurrency
		return ret
	}
	return *o.CurrencyFiat
}

// GetCurrencyFiatOk returns a tuple with the CurrencyFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetCurrencyFiatOk() (*FiatCurrency, bool) {
	if o == nil || IsNil(o.CurrencyFiat) {
		return nil, false
	}
	return o.CurrencyFiat, true
}

// HasCurrencyFiat returns a boolean if a field has been set.
func (o *WebhookPayload) HasCurrencyFiat() bool {
	if o != nil && !IsNil(o.CurrencyFiat) {
		return true
	}

	return false
}

// SetCurrencyFiat gets a reference to the given FiatCurrency and assigns it to the CurrencyFiat field.
func (o *WebhookPayload) SetCurrencyFiat(v FiatCurrency) {
	o.CurrencyFiat = &v
}

// GetAmountFiat returns the AmountFiat field value if set, zero value otherwise.
func (o *WebhookPayload) GetAmountFiat() string {
	if o == nil || IsNil(o.AmountFiat) {
		var ret string
		return ret
	}
	return *o.AmountFiat
}

// GetAmountFiatOk returns a tuple with the AmountFiat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetAmountFiatOk() (*string, bool) {
	if o == nil || IsNil(o.AmountFiat) {
		return nil, false
	}
	return o.AmountFiat, true
}

// HasAmountFiat returns a boolean if a field has been set.
func (o *WebhookPayload) HasAmountFiat() bool {
	if o != nil && !IsNil(o.AmountFiat) {
		return true
	}

	return false
}

// SetAmountFiat gets a reference to the given string and assigns it to the AmountFiat field.
func (o *WebhookPayload) SetAmountFiat(v string) {
	o.AmountFiat = &v
}

// GetAmountUsd returns the AmountUsd field value if set, zero value otherwise.
func (o *WebhookPayload) GetAmountUsd() string {
	if o == nil || IsNil(o.AmountUsd) {
		var ret string
		return ret
	}
	return *o.AmountUsd
}

// GetAmountUsdOk returns a tuple with the AmountUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetAmountUsdOk() (*string, bool) {
	if o == nil || IsNil(o.AmountUsd) {
		return nil, false
	}
	return o.AmountUsd, true
}

// HasAmountUsd returns a boolean if a field has been set.
func (o *WebhookPayload) HasAmountUsd() bool {
	if o != nil && !IsNil(o.AmountUsd) {
		return true
	}

	return false
}

// SetAmountUsd gets a reference to the given string and assigns it to the AmountUsd field.
func (o *WebhookPayload) SetAmountUsd(v string) {
	o.AmountUsd = &v
}

// GetAmountCrypto returns the AmountCrypto field value if set, zero value otherwise.
func (o *WebhookPayload) GetAmountCrypto() string {
	if o == nil || IsNil(o.AmountCrypto) {
		var ret string
		return ret
	}
	return *o.AmountCrypto
}

// GetAmountCryptoOk returns a tuple with the AmountCrypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetAmountCryptoOk() (*string, bool) {
	if o == nil || IsNil(o.AmountCrypto) {
		return nil, false
	}
	return o.AmountCrypto, true
}

// HasAmountCrypto returns a boolean if a field has been set.
func (o *WebhookPayload) HasAmountCrypto() bool {
	if o != nil && !IsNil(o.AmountCrypto) {
		return true
	}

	return false
}

// SetAmountCrypto gets a reference to the given string and assigns it to the AmountCrypto field.
func (o *WebhookPayload) SetAmountCrypto(v string) {
	o.AmountCrypto = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookPayload) GetOrderId() string {
	if o == nil || IsNil(o.OrderId.Get()) {
		var ret string
		return ret
	}
	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookPayload) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// HasOrderId returns a boolean if a field has been set.
func (o *WebhookPayload) HasOrderId() bool {
	if o != nil && o.OrderId.IsSet() {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given NullableString and assigns it to the OrderId field.
func (o *WebhookPayload) SetOrderId(v string) {
	o.OrderId.Set(&v)
}
// SetOrderIdNil sets the value for OrderId to be an explicit nil
func (o *WebhookPayload) SetOrderIdNil() {
	o.OrderId.Set(nil)
}

// UnsetOrderId ensures that no value is present for OrderId, not even an explicit nil
func (o *WebhookPayload) UnsetOrderId() {
	o.OrderId.Unset()
}

// GetReceiptUrl returns the ReceiptUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookPayload) GetReceiptUrl() string {
	if o == nil || IsNil(o.ReceiptUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ReceiptUrl.Get()
}

// GetReceiptUrlOk returns a tuple with the ReceiptUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookPayload) GetReceiptUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceiptUrl.Get(), o.ReceiptUrl.IsSet()
}

// HasReceiptUrl returns a boolean if a field has been set.
func (o *WebhookPayload) HasReceiptUrl() bool {
	if o != nil && o.ReceiptUrl.IsSet() {
		return true
	}

	return false
}

// SetReceiptUrl gets a reference to the given NullableString and assigns it to the ReceiptUrl field.
func (o *WebhookPayload) SetReceiptUrl(v string) {
	o.ReceiptUrl.Set(&v)
}
// SetReceiptUrlNil sets the value for ReceiptUrl to be an explicit nil
func (o *WebhookPayload) SetReceiptUrlNil() {
	o.ReceiptUrl.Set(nil)
}

// UnsetReceiptUrl ensures that no value is present for ReceiptUrl, not even an explicit nil
func (o *WebhookPayload) UnsetReceiptUrl() {
	o.ReceiptUrl.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *WebhookPayload) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookPayload) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *WebhookPayload) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *WebhookPayload) SetMetadata(v map[string]string) {
	o.Metadata = v
}

func (o WebhookPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["status"] = o.Status
	if !IsNil(o.CurrencyCrypto) {
		toSerialize["currency_crypto"] = o.CurrencyCrypto
	}
	if !IsNil(o.CurrencyFiat) {
		toSerialize["currency_fiat"] = o.CurrencyFiat
	}
	if !IsNil(o.AmountFiat) {
		toSerialize["amount_fiat"] = o.AmountFiat
	}
	if !IsNil(o.AmountUsd) {
		toSerialize["amount_usd"] = o.AmountUsd
	}
	if !IsNil(o.AmountCrypto) {
		toSerialize["amount_crypto"] = o.AmountCrypto
	}
	if o.OrderId.IsSet() {
		toSerialize["order_id"] = o.OrderId.Get()
	}
	if o.ReceiptUrl.IsSet() {
		toSerialize["receipt_url"] = o.ReceiptUrl.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *WebhookPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"timestamp",
		"transaction_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookPayload := _WebhookPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookPayload)

	if err != nil {
		return err
	}

	*o = WebhookPayload(varWebhookPayload)

	return err
}

type NullableWebhookPayload struct {
	value *WebhookPayload
	isSet bool
}

func (v NullableWebhookPayload) Get() *WebhookPayload {
	return v.value
}

func (v *NullableWebhookPayload) Set(val *WebhookPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPayload(val *WebhookPayload) *NullableWebhookPayload {
	return &NullableWebhookPayload{value: val, isSet: true}
}

func (v NullableWebhookPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


