/*
GriffNode API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package griffnode

import (
	"encoding/json"
)

// checks if the ListCryptocurrencies200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCryptocurrencies200ResponseData{}

// ListCryptocurrencies200ResponseData struct for ListCryptocurrencies200ResponseData
type ListCryptocurrencies200ResponseData struct {
	Cryptocurrencies []Cryptocurrency `json:"cryptocurrencies,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewListCryptocurrencies200ResponseData instantiates a new ListCryptocurrencies200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCryptocurrencies200ResponseData() *ListCryptocurrencies200ResponseData {
	this := ListCryptocurrencies200ResponseData{}
	return &this
}

// NewListCryptocurrencies200ResponseDataWithDefaults instantiates a new ListCryptocurrencies200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCryptocurrencies200ResponseDataWithDefaults() *ListCryptocurrencies200ResponseData {
	this := ListCryptocurrencies200ResponseData{}
	return &this
}

// GetCryptocurrencies returns the Cryptocurrencies field value if set, zero value otherwise.
func (o *ListCryptocurrencies200ResponseData) GetCryptocurrencies() []Cryptocurrency {
	if o == nil || IsNil(o.Cryptocurrencies) {
		var ret []Cryptocurrency
		return ret
	}
	return o.Cryptocurrencies
}

// GetCryptocurrenciesOk returns a tuple with the Cryptocurrencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCryptocurrencies200ResponseData) GetCryptocurrenciesOk() ([]Cryptocurrency, bool) {
	if o == nil || IsNil(o.Cryptocurrencies) {
		return nil, false
	}
	return o.Cryptocurrencies, true
}

// HasCryptocurrencies returns a boolean if a field has been set.
func (o *ListCryptocurrencies200ResponseData) HasCryptocurrencies() bool {
	if o != nil && !IsNil(o.Cryptocurrencies) {
		return true
	}

	return false
}

// SetCryptocurrencies gets a reference to the given []Cryptocurrency and assigns it to the Cryptocurrencies field.
func (o *ListCryptocurrencies200ResponseData) SetCryptocurrencies(v []Cryptocurrency) {
	o.Cryptocurrencies = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListCryptocurrencies200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCryptocurrencies200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListCryptocurrencies200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListCryptocurrencies200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

func (o ListCryptocurrencies200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCryptocurrencies200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cryptocurrencies) {
		toSerialize["cryptocurrencies"] = o.Cryptocurrencies
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableListCryptocurrencies200ResponseData struct {
	value *ListCryptocurrencies200ResponseData
	isSet bool
}

func (v NullableListCryptocurrencies200ResponseData) Get() *ListCryptocurrencies200ResponseData {
	return v.value
}

func (v *NullableListCryptocurrencies200ResponseData) Set(val *ListCryptocurrencies200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListCryptocurrencies200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListCryptocurrencies200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCryptocurrencies200ResponseData(val *ListCryptocurrencies200ResponseData) *NullableListCryptocurrencies200ResponseData {
	return &NullableListCryptocurrencies200ResponseData{value: val, isSet: true}
}

func (v NullableListCryptocurrencies200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCryptocurrencies200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


