/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Transaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transaction{}

// Transaction The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
type Transaction struct {
	TransactionId string `json:"transaction_id"`
	Status TransactionStatus `json:"status"`
	Type *string `json:"type,omitempty"`
	Crypto CryptoSymbol `json:"crypto"`
	DepositAddress *string `json:"deposit_address,omitempty"`
	AmountCrypto *float32 `json:"amount_crypto,omitempty"`
	AmountFiat float32 `json:"amount_fiat"`
	AmountUsd float32 `json:"amount_usd"`
	AmountPaid *float32 `json:"amount_paid,omitempty"`
	AmountRemaining *float32 `json:"amount_remaining,omitempty"`
	CurrencyFiat FiatCurrency `json:"currency_fiat"`
	FiatToUsdRate *float32 `json:"fiat_to_usd_rate,omitempty"`
	// USD per unit of crypto, locked at creation.
	ExchangeRate *float32 `json:"exchange_rate,omitempty"`
	ConfirmationsRequired *int32 `json:"confirmations_required,omitempty"`
	PaymentUrl *string `json:"payment_url,omitempty"`
	OrderId NullableString `json:"order_id,omitempty"`
	CustomerEmail NullableString `json:"customer_email,omitempty"`
	Items []LineItem `json:"items,omitempty"`
	// On-chain payments detected toward this transaction.
	Payments []PaymentSplit `json:"payments,omitempty"`
	// Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
	Metadata map[string]string `json:"metadata,omitempty"`
	SuccessUrl NullableString `json:"success_url,omitempty"`
	CancelUrl NullableString `json:"cancel_url,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	ExpiresAt time.Time `json:"expires_at"`
}

type _Transaction Transaction

// NewTransaction instantiates a new Transaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransaction(transactionId string, status TransactionStatus, crypto CryptoSymbol, amountFiat float32, amountUsd float32, currencyFiat FiatCurrency, createdAt time.Time, expiresAt time.Time) *Transaction {
	this := Transaction{}
	this.TransactionId = transactionId
	this.Status = status
	this.Crypto = crypto
	this.AmountFiat = amountFiat
	this.AmountUsd = amountUsd
	this.CurrencyFiat = currencyFiat
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewTransactionWithDefaults instantiates a new Transaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionWithDefaults() *Transaction {
	this := Transaction{}
	var currencyFiat FiatCurrency = FIATCURRENCY_USD
	this.CurrencyFiat = currencyFiat
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *Transaction) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *Transaction) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetStatus returns the Status field value
func (o *Transaction) GetStatus() TransactionStatus {
	if o == nil {
		var ret TransactionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetStatusOk() (*TransactionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Transaction) SetStatus(v TransactionStatus) {
	o.Status = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Transaction) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Transaction) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Transaction) SetType(v string) {
	o.Type = &v
}

// GetCrypto returns the Crypto field value
func (o *Transaction) GetCrypto() CryptoSymbol {
	if o == nil {
		var ret CryptoSymbol
		return ret
	}

	return o.Crypto
}

// GetCryptoOk returns a tuple with the Crypto field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetCryptoOk() (*CryptoSymbol, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Crypto, true
}

// SetCrypto sets field value
func (o *Transaction) SetCrypto(v CryptoSymbol) {
	o.Crypto = v
}

// GetDepositAddress returns the DepositAddress field value if set, zero value otherwise.
func (o *Transaction) GetDepositAddress() string {
	if o == nil || IsNil(o.DepositAddress) {
		var ret string
		return ret
	}
	return *o.DepositAddress
}

// GetDepositAddressOk returns a tuple with the DepositAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetDepositAddressOk() (*string, bool) {
	if o == nil || IsNil(o.DepositAddress) {
		return nil, false
	}
	return o.DepositAddress, true
}

// HasDepositAddress returns a boolean if a field has been set.
func (o *Transaction) HasDepositAddress() bool {
	if o != nil && !IsNil(o.DepositAddress) {
		return true
	}

	return false
}

// SetDepositAddress gets a reference to the given string and assigns it to the DepositAddress field.
func (o *Transaction) SetDepositAddress(v string) {
	o.DepositAddress = &v
}

// GetAmountCrypto returns the AmountCrypto field value if set, zero value otherwise.
func (o *Transaction) GetAmountCrypto() float32 {
	if o == nil || IsNil(o.AmountCrypto) {
		var ret float32
		return ret
	}
	return *o.AmountCrypto
}

// GetAmountCryptoOk returns a tuple with the AmountCrypto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountCryptoOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountCrypto) {
		return nil, false
	}
	return o.AmountCrypto, true
}

// HasAmountCrypto returns a boolean if a field has been set.
func (o *Transaction) HasAmountCrypto() bool {
	if o != nil && !IsNil(o.AmountCrypto) {
		return true
	}

	return false
}

// SetAmountCrypto gets a reference to the given float32 and assigns it to the AmountCrypto field.
func (o *Transaction) SetAmountCrypto(v float32) {
	o.AmountCrypto = &v
}

// GetAmountFiat returns the AmountFiat field value
func (o *Transaction) GetAmountFiat() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AmountFiat
}

// GetAmountFiatOk returns a tuple with the AmountFiat field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountFiatOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountFiat, true
}

// SetAmountFiat sets field value
func (o *Transaction) SetAmountFiat(v float32) {
	o.AmountFiat = v
}

// GetAmountUsd returns the AmountUsd field value
func (o *Transaction) GetAmountUsd() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AmountUsd
}

// GetAmountUsdOk returns a tuple with the AmountUsd field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountUsd, true
}

// SetAmountUsd sets field value
func (o *Transaction) SetAmountUsd(v float32) {
	o.AmountUsd = v
}

// GetAmountPaid returns the AmountPaid field value if set, zero value otherwise.
func (o *Transaction) GetAmountPaid() float32 {
	if o == nil || IsNil(o.AmountPaid) {
		var ret float32
		return ret
	}
	return *o.AmountPaid
}

// GetAmountPaidOk returns a tuple with the AmountPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountPaidOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountPaid) {
		return nil, false
	}
	return o.AmountPaid, true
}

// HasAmountPaid returns a boolean if a field has been set.
func (o *Transaction) HasAmountPaid() bool {
	if o != nil && !IsNil(o.AmountPaid) {
		return true
	}

	return false
}

// SetAmountPaid gets a reference to the given float32 and assigns it to the AmountPaid field.
func (o *Transaction) SetAmountPaid(v float32) {
	o.AmountPaid = &v
}

// GetAmountRemaining returns the AmountRemaining field value if set, zero value otherwise.
func (o *Transaction) GetAmountRemaining() float32 {
	if o == nil || IsNil(o.AmountRemaining) {
		var ret float32
		return ret
	}
	return *o.AmountRemaining
}

// GetAmountRemainingOk returns a tuple with the AmountRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetAmountRemainingOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountRemaining) {
		return nil, false
	}
	return o.AmountRemaining, true
}

// HasAmountRemaining returns a boolean if a field has been set.
func (o *Transaction) HasAmountRemaining() bool {
	if o != nil && !IsNil(o.AmountRemaining) {
		return true
	}

	return false
}

// SetAmountRemaining gets a reference to the given float32 and assigns it to the AmountRemaining field.
func (o *Transaction) SetAmountRemaining(v float32) {
	o.AmountRemaining = &v
}

// GetCurrencyFiat returns the CurrencyFiat field value
func (o *Transaction) GetCurrencyFiat() FiatCurrency {
	if o == nil {
		var ret FiatCurrency
		return ret
	}

	return o.CurrencyFiat
}

// GetCurrencyFiatOk returns a tuple with the CurrencyFiat field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetCurrencyFiatOk() (*FiatCurrency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyFiat, true
}

// SetCurrencyFiat sets field value
func (o *Transaction) SetCurrencyFiat(v FiatCurrency) {
	o.CurrencyFiat = v
}

// GetFiatToUsdRate returns the FiatToUsdRate field value if set, zero value otherwise.
func (o *Transaction) GetFiatToUsdRate() float32 {
	if o == nil || IsNil(o.FiatToUsdRate) {
		var ret float32
		return ret
	}
	return *o.FiatToUsdRate
}

// GetFiatToUsdRateOk returns a tuple with the FiatToUsdRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetFiatToUsdRateOk() (*float32, bool) {
	if o == nil || IsNil(o.FiatToUsdRate) {
		return nil, false
	}
	return o.FiatToUsdRate, true
}

// HasFiatToUsdRate returns a boolean if a field has been set.
func (o *Transaction) HasFiatToUsdRate() bool {
	if o != nil && !IsNil(o.FiatToUsdRate) {
		return true
	}

	return false
}

// SetFiatToUsdRate gets a reference to the given float32 and assigns it to the FiatToUsdRate field.
func (o *Transaction) SetFiatToUsdRate(v float32) {
	o.FiatToUsdRate = &v
}

// GetExchangeRate returns the ExchangeRate field value if set, zero value otherwise.
func (o *Transaction) GetExchangeRate() float32 {
	if o == nil || IsNil(o.ExchangeRate) {
		var ret float32
		return ret
	}
	return *o.ExchangeRate
}

// GetExchangeRateOk returns a tuple with the ExchangeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetExchangeRateOk() (*float32, bool) {
	if o == nil || IsNil(o.ExchangeRate) {
		return nil, false
	}
	return o.ExchangeRate, true
}

// HasExchangeRate returns a boolean if a field has been set.
func (o *Transaction) HasExchangeRate() bool {
	if o != nil && !IsNil(o.ExchangeRate) {
		return true
	}

	return false
}

// SetExchangeRate gets a reference to the given float32 and assigns it to the ExchangeRate field.
func (o *Transaction) SetExchangeRate(v float32) {
	o.ExchangeRate = &v
}

// GetConfirmationsRequired returns the ConfirmationsRequired field value if set, zero value otherwise.
func (o *Transaction) GetConfirmationsRequired() int32 {
	if o == nil || IsNil(o.ConfirmationsRequired) {
		var ret int32
		return ret
	}
	return *o.ConfirmationsRequired
}

// GetConfirmationsRequiredOk returns a tuple with the ConfirmationsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetConfirmationsRequiredOk() (*int32, bool) {
	if o == nil || IsNil(o.ConfirmationsRequired) {
		return nil, false
	}
	return o.ConfirmationsRequired, true
}

// HasConfirmationsRequired returns a boolean if a field has been set.
func (o *Transaction) HasConfirmationsRequired() bool {
	if o != nil && !IsNil(o.ConfirmationsRequired) {
		return true
	}

	return false
}

// SetConfirmationsRequired gets a reference to the given int32 and assigns it to the ConfirmationsRequired field.
func (o *Transaction) SetConfirmationsRequired(v int32) {
	o.ConfirmationsRequired = &v
}

// GetPaymentUrl returns the PaymentUrl field value if set, zero value otherwise.
func (o *Transaction) GetPaymentUrl() string {
	if o == nil || IsNil(o.PaymentUrl) {
		var ret string
		return ret
	}
	return *o.PaymentUrl
}

// GetPaymentUrlOk returns a tuple with the PaymentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPaymentUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentUrl) {
		return nil, false
	}
	return o.PaymentUrl, true
}

// HasPaymentUrl returns a boolean if a field has been set.
func (o *Transaction) HasPaymentUrl() bool {
	if o != nil && !IsNil(o.PaymentUrl) {
		return true
	}

	return false
}

// SetPaymentUrl gets a reference to the given string and assigns it to the PaymentUrl field.
func (o *Transaction) SetPaymentUrl(v string) {
	o.PaymentUrl = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetOrderId() string {
	if o == nil || IsNil(o.OrderId.Get()) {
		var ret string
		return ret
	}
	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// HasOrderId returns a boolean if a field has been set.
func (o *Transaction) HasOrderId() bool {
	if o != nil && o.OrderId.IsSet() {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given NullableString and assigns it to the OrderId field.
func (o *Transaction) SetOrderId(v string) {
	o.OrderId.Set(&v)
}
// SetOrderIdNil sets the value for OrderId to be an explicit nil
func (o *Transaction) SetOrderIdNil() {
	o.OrderId.Set(nil)
}

// UnsetOrderId ensures that no value is present for OrderId, not even an explicit nil
func (o *Transaction) UnsetOrderId() {
	o.OrderId.Unset()
}

// GetCustomerEmail returns the CustomerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetCustomerEmail() string {
	if o == nil || IsNil(o.CustomerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerEmail.Get()
}

// GetCustomerEmailOk returns a tuple with the CustomerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetCustomerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerEmail.Get(), o.CustomerEmail.IsSet()
}

// HasCustomerEmail returns a boolean if a field has been set.
func (o *Transaction) HasCustomerEmail() bool {
	if o != nil && o.CustomerEmail.IsSet() {
		return true
	}

	return false
}

// SetCustomerEmail gets a reference to the given NullableString and assigns it to the CustomerEmail field.
func (o *Transaction) SetCustomerEmail(v string) {
	o.CustomerEmail.Set(&v)
}
// SetCustomerEmailNil sets the value for CustomerEmail to be an explicit nil
func (o *Transaction) SetCustomerEmailNil() {
	o.CustomerEmail.Set(nil)
}

// UnsetCustomerEmail ensures that no value is present for CustomerEmail, not even an explicit nil
func (o *Transaction) UnsetCustomerEmail() {
	o.CustomerEmail.Unset()
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetItems() []LineItem {
	if o == nil {
		var ret []LineItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetItemsOk() ([]LineItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *Transaction) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []LineItem and assigns it to the Items field.
func (o *Transaction) SetItems(v []LineItem) {
	o.Items = v
}

// GetPayments returns the Payments field value if set, zero value otherwise.
func (o *Transaction) GetPayments() []PaymentSplit {
	if o == nil || IsNil(o.Payments) {
		var ret []PaymentSplit
		return ret
	}
	return o.Payments
}

// GetPaymentsOk returns a tuple with the Payments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetPaymentsOk() ([]PaymentSplit, bool) {
	if o == nil || IsNil(o.Payments) {
		return nil, false
	}
	return o.Payments, true
}

// HasPayments returns a boolean if a field has been set.
func (o *Transaction) HasPayments() bool {
	if o != nil && !IsNil(o.Payments) {
		return true
	}

	return false
}

// SetPayments gets a reference to the given []PaymentSplit and assigns it to the Payments field.
func (o *Transaction) SetPayments(v []PaymentSplit) {
	o.Payments = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Transaction) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Transaction) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *Transaction) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetSuccessUrl returns the SuccessUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetSuccessUrl() string {
	if o == nil || IsNil(o.SuccessUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SuccessUrl.Get()
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuccessUrl.Get(), o.SuccessUrl.IsSet()
}

// HasSuccessUrl returns a boolean if a field has been set.
func (o *Transaction) HasSuccessUrl() bool {
	if o != nil && o.SuccessUrl.IsSet() {
		return true
	}

	return false
}

// SetSuccessUrl gets a reference to the given NullableString and assigns it to the SuccessUrl field.
func (o *Transaction) SetSuccessUrl(v string) {
	o.SuccessUrl.Set(&v)
}
// SetSuccessUrlNil sets the value for SuccessUrl to be an explicit nil
func (o *Transaction) SetSuccessUrlNil() {
	o.SuccessUrl.Set(nil)
}

// UnsetSuccessUrl ensures that no value is present for SuccessUrl, not even an explicit nil
func (o *Transaction) UnsetSuccessUrl() {
	o.SuccessUrl.Unset()
}

// GetCancelUrl returns the CancelUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetCancelUrl() string {
	if o == nil || IsNil(o.CancelUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CancelUrl.Get()
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancelUrl.Get(), o.CancelUrl.IsSet()
}

// HasCancelUrl returns a boolean if a field has been set.
func (o *Transaction) HasCancelUrl() bool {
	if o != nil && o.CancelUrl.IsSet() {
		return true
	}

	return false
}

// SetCancelUrl gets a reference to the given NullableString and assigns it to the CancelUrl field.
func (o *Transaction) SetCancelUrl(v string) {
	o.CancelUrl.Set(&v)
}
// SetCancelUrlNil sets the value for CancelUrl to be an explicit nil
func (o *Transaction) SetCancelUrlNil() {
	o.CancelUrl.Set(nil)
}

// UnsetCancelUrl ensures that no value is present for CancelUrl, not even an explicit nil
func (o *Transaction) UnsetCancelUrl() {
	o.CancelUrl.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *Transaction) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Transaction) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Transaction) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transaction) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Transaction) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Transaction) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *Transaction) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *Transaction) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o Transaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["status"] = o.Status
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["crypto"] = o.Crypto
	if !IsNil(o.DepositAddress) {
		toSerialize["deposit_address"] = o.DepositAddress
	}
	if !IsNil(o.AmountCrypto) {
		toSerialize["amount_crypto"] = o.AmountCrypto
	}
	toSerialize["amount_fiat"] = o.AmountFiat
	toSerialize["amount_usd"] = o.AmountUsd
	if !IsNil(o.AmountPaid) {
		toSerialize["amount_paid"] = o.AmountPaid
	}
	if !IsNil(o.AmountRemaining) {
		toSerialize["amount_remaining"] = o.AmountRemaining
	}
	toSerialize["currency_fiat"] = o.CurrencyFiat
	if !IsNil(o.FiatToUsdRate) {
		toSerialize["fiat_to_usd_rate"] = o.FiatToUsdRate
	}
	if !IsNil(o.ExchangeRate) {
		toSerialize["exchange_rate"] = o.ExchangeRate
	}
	if !IsNil(o.ConfirmationsRequired) {
		toSerialize["confirmations_required"] = o.ConfirmationsRequired
	}
	if !IsNil(o.PaymentUrl) {
		toSerialize["payment_url"] = o.PaymentUrl
	}
	if o.OrderId.IsSet() {
		toSerialize["order_id"] = o.OrderId.Get()
	}
	if o.CustomerEmail.IsSet() {
		toSerialize["customer_email"] = o.CustomerEmail.Get()
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Payments) {
		toSerialize["payments"] = o.Payments
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.SuccessUrl.IsSet() {
		toSerialize["success_url"] = o.SuccessUrl.Get()
	}
	if o.CancelUrl.IsSet() {
		toSerialize["cancel_url"] = o.CancelUrl.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *Transaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_id",
		"status",
		"crypto",
		"amount_fiat",
		"amount_usd",
		"currency_fiat",
		"created_at",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransaction := _Transaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransaction)

	if err != nil {
		return err
	}

	*o = Transaction(varTransaction)

	return err
}

type NullableTransaction struct {
	value *Transaction
	isSet bool
}

func (v NullableTransaction) Get() *Transaction {
	return v.value
}

func (v *NullableTransaction) Set(val *Transaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransaction(val *Transaction) *NullableTransaction {
	return &NullableTransaction{value: val, isSet: true}
}

func (v NullableTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


