/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the InlineObjectAllOfExistingTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObjectAllOfExistingTransaction{}

// InlineObjectAllOfExistingTransaction struct for InlineObjectAllOfExistingTransaction
type InlineObjectAllOfExistingTransaction struct {
	TransactionId *string `json:"transaction_id,omitempty"`
	Status *TransactionStatus `json:"status,omitempty"`
	PaymentUrl *string `json:"payment_url,omitempty"`
}

// NewInlineObjectAllOfExistingTransaction instantiates a new InlineObjectAllOfExistingTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObjectAllOfExistingTransaction() *InlineObjectAllOfExistingTransaction {
	this := InlineObjectAllOfExistingTransaction{}
	return &this
}

// NewInlineObjectAllOfExistingTransactionWithDefaults instantiates a new InlineObjectAllOfExistingTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObjectAllOfExistingTransactionWithDefaults() *InlineObjectAllOfExistingTransaction {
	this := InlineObjectAllOfExistingTransaction{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *InlineObjectAllOfExistingTransaction) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObjectAllOfExistingTransaction) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *InlineObjectAllOfExistingTransaction) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *InlineObjectAllOfExistingTransaction) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineObjectAllOfExistingTransaction) GetStatus() TransactionStatus {
	if o == nil || IsNil(o.Status) {
		var ret TransactionStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObjectAllOfExistingTransaction) GetStatusOk() (*TransactionStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineObjectAllOfExistingTransaction) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TransactionStatus and assigns it to the Status field.
func (o *InlineObjectAllOfExistingTransaction) SetStatus(v TransactionStatus) {
	o.Status = &v
}

// GetPaymentUrl returns the PaymentUrl field value if set, zero value otherwise.
func (o *InlineObjectAllOfExistingTransaction) GetPaymentUrl() string {
	if o == nil || IsNil(o.PaymentUrl) {
		var ret string
		return ret
	}
	return *o.PaymentUrl
}

// GetPaymentUrlOk returns a tuple with the PaymentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObjectAllOfExistingTransaction) GetPaymentUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentUrl) {
		return nil, false
	}
	return o.PaymentUrl, true
}

// HasPaymentUrl returns a boolean if a field has been set.
func (o *InlineObjectAllOfExistingTransaction) HasPaymentUrl() bool {
	if o != nil && !IsNil(o.PaymentUrl) {
		return true
	}

	return false
}

// SetPaymentUrl gets a reference to the given string and assigns it to the PaymentUrl field.
func (o *InlineObjectAllOfExistingTransaction) SetPaymentUrl(v string) {
	o.PaymentUrl = &v
}

func (o InlineObjectAllOfExistingTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObjectAllOfExistingTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PaymentUrl) {
		toSerialize["payment_url"] = o.PaymentUrl
	}
	return toSerialize, nil
}

type NullableInlineObjectAllOfExistingTransaction struct {
	value *InlineObjectAllOfExistingTransaction
	isSet bool
}

func (v NullableInlineObjectAllOfExistingTransaction) Get() *InlineObjectAllOfExistingTransaction {
	return v.value
}

func (v *NullableInlineObjectAllOfExistingTransaction) Set(val *InlineObjectAllOfExistingTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObjectAllOfExistingTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObjectAllOfExistingTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObjectAllOfExistingTransaction(val *InlineObjectAllOfExistingTransaction) *NullableInlineObjectAllOfExistingTransaction {
	return &NullableInlineObjectAllOfExistingTransaction{value: val, isSet: true}
}

func (v NullableInlineObjectAllOfExistingTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObjectAllOfExistingTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


