/*
CryptoGate API

Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptogate

import (
	"encoding/json"
)

// checks if the Cryptocurrency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cryptocurrency{}

// Cryptocurrency struct for Cryptocurrency
type Cryptocurrency struct {
	Symbol *CryptoSymbol `json:"symbol,omitempty"`
	Name *string `json:"name,omitempty"`
	Blockchain *string `json:"blockchain,omitempty"`
	Network *string `json:"network,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewCryptocurrency instantiates a new Cryptocurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptocurrency() *Cryptocurrency {
	this := Cryptocurrency{}
	return &this
}

// NewCryptocurrencyWithDefaults instantiates a new Cryptocurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptocurrencyWithDefaults() *Cryptocurrency {
	this := Cryptocurrency{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *Cryptocurrency) GetSymbol() CryptoSymbol {
	if o == nil || IsNil(o.Symbol) {
		var ret CryptoSymbol
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cryptocurrency) GetSymbolOk() (*CryptoSymbol, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *Cryptocurrency) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given CryptoSymbol and assigns it to the Symbol field.
func (o *Cryptocurrency) SetSymbol(v CryptoSymbol) {
	o.Symbol = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Cryptocurrency) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cryptocurrency) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Cryptocurrency) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Cryptocurrency) SetName(v string) {
	o.Name = &v
}

// GetBlockchain returns the Blockchain field value if set, zero value otherwise.
func (o *Cryptocurrency) GetBlockchain() string {
	if o == nil || IsNil(o.Blockchain) {
		var ret string
		return ret
	}
	return *o.Blockchain
}

// GetBlockchainOk returns a tuple with the Blockchain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cryptocurrency) GetBlockchainOk() (*string, bool) {
	if o == nil || IsNil(o.Blockchain) {
		return nil, false
	}
	return o.Blockchain, true
}

// HasBlockchain returns a boolean if a field has been set.
func (o *Cryptocurrency) HasBlockchain() bool {
	if o != nil && !IsNil(o.Blockchain) {
		return true
	}

	return false
}

// SetBlockchain gets a reference to the given string and assigns it to the Blockchain field.
func (o *Cryptocurrency) SetBlockchain(v string) {
	o.Blockchain = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *Cryptocurrency) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cryptocurrency) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *Cryptocurrency) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *Cryptocurrency) SetNetwork(v string) {
	o.Network = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Cryptocurrency) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cryptocurrency) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Cryptocurrency) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Cryptocurrency) SetType(v string) {
	o.Type = &v
}

func (o Cryptocurrency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cryptocurrency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Blockchain) {
		toSerialize["blockchain"] = o.Blockchain
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCryptocurrency struct {
	value *Cryptocurrency
	isSet bool
}

func (v NullableCryptocurrency) Get() *Cryptocurrency {
	return v.value
}

func (v *NullableCryptocurrency) Set(val *Cryptocurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptocurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptocurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptocurrency(val *Cryptocurrency) *NullableCryptocurrency {
	return &NullableCryptocurrency{value: val, isSet: true}
}

func (v NullableCryptocurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptocurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


